#+TITLE: SMPI Collective evaluation
#+DATE: Tue Feb 24 07:55:20 CET 2015
#+AUTHOR: mquinson
 
* People logged when experiment started:
* Hostname
paranoia-8.rennes.grid5000.fr
* System information
Linux paranoia-8.rennes.grid5000.fr 3.2.0-4-amd64 #1 SMP Debian 3.2.63-2+deb7u1 x86_64 GNU/Linux
* CPU info
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 62
model name	: Intel(R) Xeon(R) CPU E5-2660 v2 @ 2.20GHz
stepping	: 4
microcode	: 0x416
cpu MHz		: 2200.118
cache size	: 25600 KB
physical id	: 0
siblings	: 10
core id		: 0
cpu cores	: 10
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms
bogomips	: 4400.23
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 62
model name	: Intel(R) Xeon(R) CPU E5-2660 v2 @ 2.20GHz
stepping	: 4
microcode	: 0x416
cpu MHz		: 2200.118
cache size	: 25600 KB
physical id	: 0
siblings	: 10
core id		: 1
cpu cores	: 10
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms
bogomips	: 4399.87
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 2
vendor_id	: GenuineIntel
cpu family	: 6
model		: 62
model name	: Intel(R) Xeon(R) CPU E5-2660 v2 @ 2.20GHz
stepping	: 4
microcode	: 0x416
cpu MHz		: 2200.118
cache size	: 25600 KB
physical id	: 0
siblings	: 10
core id		: 2
cpu cores	: 10
apicid		: 4
initial apicid	: 4
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms
bogomips	: 4399.86
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 62
model name	: Intel(R) Xeon(R) CPU E5-2660 v2 @ 2.20GHz
stepping	: 4
microcode	: 0x416
cpu MHz		: 2200.118
cache size	: 25600 KB
physical id	: 0
siblings	: 10
core id		: 3
cpu cores	: 10
apicid		: 6
initial apicid	: 6
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms
bogomips	: 4399.86
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 4
vendor_id	: GenuineIntel
cpu family	: 6
model		: 62
model name	: Intel(R) Xeon(R) CPU E5-2660 v2 @ 2.20GHz
stepping	: 4
microcode	: 0x416
cpu MHz		: 2200.118
cache size	: 25600 KB
physical id	: 0
siblings	: 10
core id		: 4
cpu cores	: 10
apicid		: 8
initial apicid	: 8
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms
bogomips	: 4399.87
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 5
vendor_id	: GenuineIntel
cpu family	: 6
model		: 62
model name	: Intel(R) Xeon(R) CPU E5-2660 v2 @ 2.20GHz
stepping	: 4
microcode	: 0x416
cpu MHz		: 2200.118
cache size	: 25600 KB
physical id	: 0
siblings	: 10
core id		: 8
cpu cores	: 10
apicid		: 16
initial apicid	: 16
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms
bogomips	: 4399.86
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 6
vendor_id	: GenuineIntel
cpu family	: 6
model		: 62
model name	: Intel(R) Xeon(R) CPU E5-2660 v2 @ 2.20GHz
stepping	: 4
microcode	: 0x416
cpu MHz		: 2200.118
cache size	: 25600 KB
physical id	: 0
siblings	: 10
core id		: 9
cpu cores	: 10
apicid		: 18
initial apicid	: 18
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms
bogomips	: 4399.86
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 7
vendor_id	: GenuineIntel
cpu family	: 6
model		: 62
model name	: Intel(R) Xeon(R) CPU E5-2660 v2 @ 2.20GHz
stepping	: 4
microcode	: 0x416
cpu MHz		: 2200.118
cache size	: 25600 KB
physical id	: 0
siblings	: 10
core id		: 10
cpu cores	: 10
apicid		: 20
initial apicid	: 20
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms
bogomips	: 4399.86
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 8
vendor_id	: GenuineIntel
cpu family	: 6
model		: 62
model name	: Intel(R) Xeon(R) CPU E5-2660 v2 @ 2.20GHz
stepping	: 4
microcode	: 0x416
cpu MHz		: 2200.118
cache size	: 25600 KB
physical id	: 0
siblings	: 10
core id		: 11
cpu cores	: 10
apicid		: 22
initial apicid	: 22
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms
bogomips	: 4399.86
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 9
vendor_id	: GenuineIntel
cpu family	: 6
model		: 62
model name	: Intel(R) Xeon(R) CPU E5-2660 v2 @ 2.20GHz
stepping	: 4
microcode	: 0x416
cpu MHz		: 2200.118
cache size	: 25600 KB
physical id	: 0
siblings	: 10
core id		: 12
cpu cores	: 10
apicid		: 24
initial apicid	: 24
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms
bogomips	: 4399.86
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 10
vendor_id	: GenuineIntel
cpu family	: 6
model		: 62
model name	: Intel(R) Xeon(R) CPU E5-2660 v2 @ 2.20GHz
stepping	: 4
microcode	: 0x416
cpu MHz		: 2200.118
cache size	: 25600 KB
physical id	: 1
siblings	: 10
core id		: 0
cpu cores	: 10
apicid		: 32
initial apicid	: 32
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms
bogomips	: 4399.91
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 11
vendor_id	: GenuineIntel
cpu family	: 6
model		: 62
model name	: Intel(R) Xeon(R) CPU E5-2660 v2 @ 2.20GHz
stepping	: 4
microcode	: 0x416
cpu MHz		: 2200.118
cache size	: 25600 KB
physical id	: 1
siblings	: 10
core id		: 1
cpu cores	: 10
apicid		: 34
initial apicid	: 34
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms
bogomips	: 4399.88
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 12
vendor_id	: GenuineIntel
cpu family	: 6
model		: 62
model name	: Intel(R) Xeon(R) CPU E5-2660 v2 @ 2.20GHz
stepping	: 4
microcode	: 0x416
cpu MHz		: 2200.118
cache size	: 25600 KB
physical id	: 1
siblings	: 10
core id		: 2
cpu cores	: 10
apicid		: 36
initial apicid	: 36
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms
bogomips	: 4399.88
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 13
vendor_id	: GenuineIntel
cpu family	: 6
model		: 62
model name	: Intel(R) Xeon(R) CPU E5-2660 v2 @ 2.20GHz
stepping	: 4
microcode	: 0x416
cpu MHz		: 2200.118
cache size	: 25600 KB
physical id	: 1
siblings	: 10
core id		: 3
cpu cores	: 10
apicid		: 38
initial apicid	: 38
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms
bogomips	: 4399.90
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 14
vendor_id	: GenuineIntel
cpu family	: 6
model		: 62
model name	: Intel(R) Xeon(R) CPU E5-2660 v2 @ 2.20GHz
stepping	: 4
microcode	: 0x416
cpu MHz		: 2200.118
cache size	: 25600 KB
physical id	: 1
siblings	: 10
core id		: 4
cpu cores	: 10
apicid		: 40
initial apicid	: 40
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms
bogomips	: 4399.90
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 15
vendor_id	: GenuineIntel
cpu family	: 6
model		: 62
model name	: Intel(R) Xeon(R) CPU E5-2660 v2 @ 2.20GHz
stepping	: 4
microcode	: 0x416
cpu MHz		: 2200.118
cache size	: 25600 KB
physical id	: 1
siblings	: 10
core id		: 8
cpu cores	: 10
apicid		: 48
initial apicid	: 48
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms
bogomips	: 4399.88
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 16
vendor_id	: GenuineIntel
cpu family	: 6
model		: 62
model name	: Intel(R) Xeon(R) CPU E5-2660 v2 @ 2.20GHz
stepping	: 4
microcode	: 0x416
cpu MHz		: 2200.118
cache size	: 25600 KB
physical id	: 1
siblings	: 10
core id		: 9
cpu cores	: 10
apicid		: 50
initial apicid	: 50
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms
bogomips	: 4399.90
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 17
vendor_id	: GenuineIntel
cpu family	: 6
model		: 62
model name	: Intel(R) Xeon(R) CPU E5-2660 v2 @ 2.20GHz
stepping	: 4
microcode	: 0x416
cpu MHz		: 2200.118
cache size	: 25600 KB
physical id	: 1
siblings	: 10
core id		: 10
cpu cores	: 10
apicid		: 52
initial apicid	: 52
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms
bogomips	: 4399.89
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 18
vendor_id	: GenuineIntel
cpu family	: 6
model		: 62
model name	: Intel(R) Xeon(R) CPU E5-2660 v2 @ 2.20GHz
stepping	: 4
microcode	: 0x416
cpu MHz		: 2200.118
cache size	: 25600 KB
physical id	: 1
siblings	: 10
core id		: 11
cpu cores	: 10
apicid		: 54
initial apicid	: 54
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms
bogomips	: 4399.90
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 19
vendor_id	: GenuineIntel
cpu family	: 6
model		: 62
model name	: Intel(R) Xeon(R) CPU E5-2660 v2 @ 2.20GHz
stepping	: 4
microcode	: 0x416
cpu MHz		: 2200.118
cache size	: 25600 KB
physical id	: 1
siblings	: 10
core id		: 12
cpu cores	: 10
apicid		: 56
initial apicid	: 56
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms
bogomips	: 4399.89
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

* CPU governor
Unknown (information not available)
* CPU frequency
Unknown (information not available)
* Meminfo
MemTotal:       132245804 kB
MemFree:        131684568 kB
Buffers:           16644 kB
Cached:           179244 kB
SwapCached:            0 kB
Active:            77508 kB
Inactive:         141992 kB
Active(anon):      26400 kB
Inactive(anon):      700 kB
Active(file):      51108 kB
Inactive(file):   141292 kB
Unevictable:        3476 kB
Mlocked:            3476 kB
SwapTotal:       3905532 kB
SwapFree:        3905532 kB
Dirty:                32 kB
Writeback:             4 kB
AnonPages:         26288 kB
Mapped:            15016 kB
Shmem:               880 kB
Slab:              83648 kB
SReclaimable:      12876 kB
SUnreclaim:        70772 kB
KernelStack:        2496 kB
PageTables:         2548 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    70028432 kB
Committed_AS:     246048 kB
VmallocTotal:   34359738367 kB
VmallocUsed:      496992 kB
VmallocChunk:   34292146820 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:      100352 kB
DirectMap2M:     6174720 kB
DirectMap1G:    127926272 kB
* Memory hierarchy
Machine (128GB)
  NUMANode L#0 (P#0 64GB)
    Socket L#0 + L3 L#0 (25MB)
      L2 L#0 (256KB) + L1 L#0 (32KB) + Core L#0 + PU L#0 (P#0)
      L2 L#1 (256KB) + L1 L#1 (32KB) + Core L#1 + PU L#1 (P#1)
      L2 L#2 (256KB) + L1 L#2 (32KB) + Core L#2 + PU L#2 (P#2)
      L2 L#3 (256KB) + L1 L#3 (32KB) + Core L#3 + PU L#3 (P#3)
      L2 L#4 (256KB) + L1 L#4 (32KB) + Core L#4 + PU L#4 (P#4)
      L2 L#5 (256KB) + L1 L#5 (32KB) + Core L#5 + PU L#5 (P#5)
      L2 L#6 (256KB) + L1 L#6 (32KB) + Core L#6 + PU L#6 (P#6)
      L2 L#7 (256KB) + L1 L#7 (32KB) + Core L#7 + PU L#7 (P#7)
      L2 L#8 (256KB) + L1 L#8 (32KB) + Core L#8 + PU L#8 (P#8)
      L2 L#9 (256KB) + L1 L#9 (32KB) + Core L#9 + PU L#9 (P#9)
    HostBridge L#0
      PCIBridge
        PCI 8086:1521
          Net L#0 "eth2"
        PCI 8086:1521
          Net L#1 "eth3"
      PCIBridge
        PCI 8086:10fb
          Net L#2 "eth0"
        PCI 8086:10fb
          Net L#3 "eth1"
      PCIBridge
        PCIBridge
          PCI 1a03:2000
      PCI 8086:1d02
  NUMANode L#1 (P#1 64GB)
    Socket L#1 + L3 L#1 (25MB)
      L2 L#10 (256KB) + L1 L#10 (32KB) + Core L#10 + PU L#10 (P#10)
      L2 L#11 (256KB) + L1 L#11 (32KB) + Core L#11 + PU L#11 (P#11)
      L2 L#12 (256KB) + L1 L#12 (32KB) + Core L#12 + PU L#12 (P#12)
      L2 L#13 (256KB) + L1 L#13 (32KB) + Core L#13 + PU L#13 (P#13)
      L2 L#14 (256KB) + L1 L#14 (32KB) + Core L#14 + PU L#14 (P#14)
      L2 L#15 (256KB) + L1 L#15 (32KB) + Core L#15 + PU L#15 (P#15)
      L2 L#16 (256KB) + L1 L#16 (32KB) + Core L#16 + PU L#16 (P#16)
      L2 L#17 (256KB) + L1 L#17 (32KB) + Core L#17 + PU L#17 (P#17)
      L2 L#18 (256KB) + L1 L#18 (32KB) + Core L#18 + PU L#18 (P#18)
      L2 L#19 (256KB) + L1 L#19 (32KB) + Core L#19 + PU L#19 (P#19)
    HostBridge L#5
      PCIBridge
        PCI 1000:0072
          Block L#4 "sda"
          Block L#5 "sdb"
          Block L#6 "sdc"
          Block L#7 "sdd"
          Block L#8 "sde"
* Environment Variables
OAR_JOBID=701465
OAR_ARRAYID=701465
OARDIR=/usr/lib/oar
OAR_WORKING_DIRECTORY=/home/mquinson
TERM=unknown
SHELL=/bin/bash
XDG_SESSION_COOKIE=c58e076c93e6df09e57173ea547dcbf2-1424760919.890568-1818443351
PERL5LIB=/usr/lib/oar
OARCONFFILE=/etc/oar/oar.conf
OAR_USER=mquinson
LC_ALL=en_US.UTF-8
USER=mquinson
OAR_WORKDIR=/home/mquinson
OARUSER=oar
OAR_JOB_NAME=
OAR_NODE_FILE=/var/lib/oar/701465
OAR_KEY=1
OAR_RESOURCE_PROPERTIES_FILE=/var/lib/oar/701465_resources
PATH=/home/mquinson/simgrid-3.12/bin:/usr/lib/oar/oardodo:/usr/lib/oar/oardodo:/usr/local/bin:/usr/bin:/bin:/grid5000/code/bin
OAR_PROJECT_NAME=default
OAR_JOB_WALLTIME_SECONDS=259200
OAR_STDERR=OAR.701465.stderr
PWD=/home/mquinson/Code/SMPI-modeling/collectives
LANG=en_US.UTF-8
OAR_ARRAY_ID=701465
SUDO_COMMAND=OAR
OAR_FILE_NODES=/var/lib/oar/701465
SHLVL=3
HOME=/home/mquinson
LANGUAGE=en_US:en
OAR_ARRAYINDEX=1
OARXAUTHLOCATION=/usr/bin/xauth
OAR_JOB_WALLTIME=72:0:0
BASH_ENV=/home/mquinson/.bashrc
OAR_NODEFILE=/var/lib/oar/701465
LOGNAME=mquinson
SSH_CONNECTION=172.16.111.110 53697 172.16.100.8 6667
OAR_RESOURCE_FILE=/var/lib/oar/701465
OAR_STDOUT=OAR.701465.stdout
OARDO_USER=oar
OAR_JOB_ID=701465
OAR_CPUSET=/oar/mquinson_701465
OAR_ARRAY_INDEX=1
OAR_O_WORKDIR=/home/mquinson
OARDO_UID=112
_=/usr/bin/printenv
* Tools Versions
** SimGrid Full Version
SimGrid version 3.12-devel
Copyright (c) 2004-2015. The Simgrid Team.
Release build at commit 5a97de8 (2015-02-18 10:05:16 +0100)
** SimGrid Commit Hash
5a97de8c98502af9f74cfceb924fa02e0fd80925
** Linux and gcc versions
Linux version 3.2.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.6.3 (Debian 4.6.3-14) ) #1 SMP Debian 3.2.63-2+deb7u1
** Gcc info
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.7/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 4.7.2-5' --with-bugurl=file:///usr/share/doc/gcc-4.7/README.Bugs --enable-languages=c,c++,go,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.7 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.7 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --with-arch-32=i586 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.7.2 (Debian 4.7.2-5) 
** Make tool
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for x86_64-pc-linux-gnu
** CMake
cmake version 2.8.9
* Compilation result
* Platform file
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid.dtd">
<platform version="3">


<config id="General">
  <prop id="workstation/model" value="compound"/>
  <prop id="network/model" value="SMPI"/>
  <prop id="network/TCP_gamma" value="4194304"/>
  <prop id="network/sender_gap" value="0"/>
  <prop id="maxmin/precision" value="1e-9"/>
  <prop id="smpi/async_small_thres" value="65536"/>
  <prop id="smpi/send_is_detached_thres" value="327680"/>
<!--  <prop id="smpi/os" value="1:8.75118726019245e-06:7.09598480584951e-10;1420:1.38989305424406e-05:2.18111838119125e-10;65536:0.000193970854779561:-4.82025737428887e-11;327680:0:0"/>-->
<!--  <prop id="smpi/or" value="1:9.3069771137911e-06:7.92179414036391e-10;1420:1.43097562292319e-05:8.66975835499791e-10;10000:1.41659209904282e-05:1.00877300603447e-09;65536:0:0"/>-->
<!--  <prop id="smpi/bw_factor" value="0:0.408465938;1420:0.913760459;65536:0.937794396"/>-->
<!--  <prop id="smpi/lat_factor" value="0:1.01;1420:4.02;65536:9.77"/>-->
<!--  -->
 <prop id="smpi/os" value="0:8.9300920419081e-06:7.65438202550106e-10;1420:1.39684254077781e-05:2.97409403415968e-10;32768:1.54082820250394e-05:2.44104034252286e-10;65536:0.000237866424242424:0;327680:0:0"/>
 <prop id="smpi/or" value="0:8.14025462333494e-06:8.3958813204998e-10;1420:1.26995184134793e-05:9.09218191293861e-10;32768:3.09570602567453e-05:6.95645307772806e-10;65536:0:0;327680:0:0"/>
 <prop id="smpi/bw_factor" value="0:0.400976530736138;1420:0.913555534273577;32768:1.07831886657594;65536:0.956083935262915;327680:0.929867998857892"/>
 <prop id="smpi/lat_factor" value="0:1.35489260823384;1420:3.43725032107889;32768:5.72164710873587;65536:11.9885319715471;327680:9.65041953605594"/>  
</config>
 
<AS id="AS_graphene" routing="Full" >
  <cluster id="AS_sgraphene1" prefix="graphene-" radical="1-256" suffix=".nancy.grid5000.fr"
           power="4.18E9" core="4" bw="1.25E8" lat="2.4E-5"
           sharing_policy="FULLDUPLEX" limiter_link="1.875E8" loopback_lat="1.5E-9" loopback_bw="6000000000"></cluster>
  <cluster id="AS_sgraphene2" prefix="graphene-" radical="257-512" suffix=".nancy.grid5000.fr"
           power="4.18E9" core="4" bw="1.25E8" lat="2.4E-5"
           sharing_policy="FULLDUPLEX" limiter_link="1.875E8" loopback_lat="1.5E-9" loopback_bw="6000000000"></cluster>
  <cluster id="AS_sgraphene3" prefix="graphene-" radical="513-784" suffix=".nancy.grid5000.fr"
           power="4.18E9" core="4" bw="1.25E8" lat="2.4E-5"
           sharing_policy="FULLDUPLEX" limiter_link="1.875E8" loopback_lat="1.5E-9" loopback_bw="6000000000"></cluster>
  <cluster id="AS_sgraphene4" prefix="graphene-" radical="785-1024" suffix=".nancy.grid5000.fr"
           power="4.18E9" core="4" bw="1.25E8" lat="2.4E-5"
           sharing_policy="FULLDUPLEX" limiter_link="1.875E8" loopback_lat="1.5E-9" loopback_bw="6000000000"></cluster>

  <link id="switch-backbone1" bandwidth="1162500000" latency="1.5E-6" sharing_policy="FULLDUPLEX"/>
  <link id="explicit-limiter1" bandwidth="1511250000" latency="0" sharing_policy="SHARED"/>

  <link id="switch-backbone2" bandwidth="1162500000" latency="1.5E-6" sharing_policy="FULLDUPLEX"/>
  <link id="explicit-limiter2" bandwidth="1511250000" latency="0" sharing_policy="SHARED"/>

  <link id="switch-backbone3" bandwidth="1162500000" latency="1.5E-6" sharing_policy="FULLDUPLEX"/>
  <link id="explicit-limiter3" bandwidth="1511250000" latency="0" sharing_policy="SHARED"/>

  <link id="switch-backbone4" bandwidth="1162500000" latency="1.5E-6" sharing_policy="FULLDUPLEX"/>
  <link id="explicit-limiter4" bandwidth="1511250000" latency="0" sharing_policy="SHARED"/>


     <ASroute src="AS_sgraphene1" dst="AS_sgraphene2"
         gw_src="graphene-AS_sgraphene1_router.nancy.grid5000.fr"
         gw_dst="graphene-AS_sgraphene2_router.nancy.grid5000.fr"
         symmetrical="NO"
         >
                <link_ctn id="switch-backbone1" direction="UP"/>
                <link_ctn id="explicit-limiter1"/>
                <link_ctn id="explicit-limiter2"/>
                <link_ctn id="switch-backbone2" direction="DOWN"/>
                
     </ASroute>
     <ASroute src="AS_sgraphene2" dst="AS_sgraphene1"
         gw_src="graphene-AS_sgraphene2_router.nancy.grid5000.fr"
         gw_dst="graphene-AS_sgraphene1_router.nancy.grid5000.fr"
         symmetrical="NO"
         >
                <link_ctn id="switch-backbone2" direction="UP"/>
                <link_ctn id="explicit-limiter2"/>
                <link_ctn id="explicit-limiter1"/>
                <link_ctn id="switch-backbone1" direction="DOWN"/>
     </ASroute>
     <ASroute src="AS_sgraphene2" dst="AS_sgraphene3"
         gw_src="graphene-AS_sgraphene2_router.nancy.grid5000.fr"
         gw_dst="graphene-AS_sgraphene3_router.nancy.grid5000.fr"
          symmetrical="NO"
         >
                <link_ctn id="switch-backbone2" direction="UP"/>                
                <link_ctn id="explicit-limiter2"/>
                <link_ctn id="explicit-limiter3"/>
                <link_ctn id="switch-backbone3" direction="DOWN"/>
     </ASroute>
     <ASroute src="AS_sgraphene1" dst="AS_sgraphene3"
         gw_src="graphene-AS_sgraphene1_router.nancy.grid5000.fr"
         gw_dst="graphene-AS_sgraphene3_router.nancy.grid5000.fr"
         symmetrical="NO"         
         >
                <link_ctn id="switch-backbone1" direction="UP"/>
                <link_ctn id="explicit-limiter1"/>
                <link_ctn id="explicit-limiter3"/>
                <link_ctn id="switch-backbone3" direction="DOWN"/>
     </ASroute>
          <ASroute src="AS_sgraphene3" dst="AS_sgraphene1"
         gw_src="graphene-AS_sgraphene3_router.nancy.grid5000.fr"
         gw_dst="graphene-AS_sgraphene1_router.nancy.grid5000.fr"
         symmetrical="NO"         
         >
                <link_ctn id="switch-backbone3" direction="UP"/>
                <link_ctn id="explicit-limiter3"/>
                <link_ctn id="explicit-limiter1"/>
                <link_ctn id="switch-backbone1" direction="DOWN"/>
     </ASroute>
     
          <ASroute src="AS_sgraphene1" dst="AS_sgraphene4"
         gw_src="graphene-AS_sgraphene1_router.nancy.grid5000.fr"
         gw_dst="graphene-AS_sgraphene4_router.nancy.grid5000.fr"
         symmetrical="NO"         
         >
                <link_ctn id="switch-backbone1" direction="UP"/>
                <link_ctn id="explicit-limiter1"/>
                <link_ctn id="explicit-limiter4"/>
                <link_ctn id="switch-backbone4" direction="DOWN"/>
     </ASroute>
               <ASroute src="AS_sgraphene4" dst="AS_sgraphene1"
         gw_src="graphene-AS_sgraphene4_router.nancy.grid5000.fr"
         gw_dst="graphene-AS_sgraphene1_router.nancy.grid5000.fr"
         symmetrical="NO"         
         >
                <link_ctn id="switch-backbone4" direction="UP"/>
                <link_ctn id="explicit-limiter4"/>
                <link_ctn id="explicit-limiter1"/>
                <link_ctn id="switch-backbone1" direction="DOWN"/>
     </ASroute>
          <ASroute src="AS_sgraphene2" dst="AS_sgraphene4"
         gw_src="graphene-AS_sgraphene2_router.nancy.grid5000.fr"
         gw_dst="graphene-AS_sgraphene4_router.nancy.grid5000.fr"
         symmetrical="NO"         
         >
                <link_ctn id="switch-backbone2" direction="UP"/>
                <link_ctn id="explicit-limiter2"/>
                <link_ctn id="explicit-limiter4"/>
                <link_ctn id="switch-backbone4" direction="DOWN"/>
     </ASroute>
          <ASroute src="AS_sgraphene3" dst="AS_sgraphene4"
         gw_src="graphene-AS_sgraphene3_router.nancy.grid5000.fr"
         gw_dst="graphene-AS_sgraphene4_router.nancy.grid5000.fr"
         symmetrical="NO"         
         >
                <link_ctn id="switch-backbone3" direction="UP"/>
                <link_ctn id="explicit-limiter3"/>
                <link_ctn id="explicit-limiter4"/>
                <link_ctn id="switch-backbone4" direction="DOWN"/>
     </ASroute>
              <ASroute src="AS_sgraphene4" dst="AS_sgraphene3"
         gw_src="graphene-AS_sgraphene4_router.nancy.grid5000.fr"
         gw_dst="graphene-AS_sgraphene3_router.nancy.grid5000.fr"
         symmetrical="NO"         
         >
                <link_ctn id="switch-backbone4" direction="UP"/>
                <link_ctn id="explicit-limiter4"/>
                <link_ctn id="explicit-limiter3"/>
                <link_ctn id="switch-backbone3" direction="DOWN"/>
     </ASroute>
     
               <ASroute src="AS_sgraphene3" dst="AS_sgraphene2"
         gw_src="graphene-AS_sgraphene3_router.nancy.grid5000.fr"
         gw_dst="graphene-AS_sgraphene2_router.nancy.grid5000.fr"
         symmetrical="NO"         
         >
                <link_ctn id="switch-backbone3" direction="UP"/>
                <link_ctn id="explicit-limiter3"/>
                <link_ctn id="explicit-limiter2"/>
                <link_ctn id="switch-backbone2" direction="DOWN"/>
     </ASroute>
     
                    <ASroute src="AS_sgraphene4" dst="AS_sgraphene2"
         gw_src="graphene-AS_sgraphene4_router.nancy.grid5000.fr"
         gw_dst="graphene-AS_sgraphene2_router.nancy.grid5000.fr"
         symmetrical="NO"         
         >
                <link_ctn id="switch-backbone4" direction="UP"/>
                <link_ctn id="explicit-limiter4"/>
                <link_ctn id="explicit-limiter2"/>
                <link_ctn id="switch-backbone2" direction="DOWN"/>
     </ASroute>
 </AS>
</platform>

* Experiment 1
Don't do proc:342 size:255545 as there is not enough memory (free mem: 131659984 kb)
Don't do proc:973 size:238223 as there is not enough memory (free mem: 131659984 kb)
Don't do proc:400 size:1168819 as there is not enough memory (free mem: 131659984 kb)
Don't do proc:739 size:502715 as there is not enough memory (free mem: 131659984 kb)
Don't do proc:376 size:1338687 as there is not enough memory (free mem: 131659984 kb)
Don't do proc:937 size:1428815 as there is not enough memory (free mem: 131659984 kb)
Do proc:438 size:38198 freemem:131659984k mem usage:33461448
** Test with algorithm 2dmesh
