#+TITLE: SMPI Collective evaluation
#+DATE: mardi 17 février 2015, 14:07:24 (UTC+0100)
#+AUTHOR: mquinson
 
* People logged when experiment started:
mquinson tty1         2015-02-03 18:47
mquinson :0           2015-02-03 18:47 (:0)
mquinson pts/1        2015-02-03 18:48 (:0.0)
mquinson pts/2        2015-02-03 22:57 (:0.0)
mquinson pts/3        2015-02-03 22:20 (:0.0)
mquinson pts/4        2015-02-03 22:45 (:0.0)
mquinson pts/5        2015-02-03 22:58 (:0.0)
mquinson pts/7        2015-02-05 16:38 (:0.0)
mquinson pts/6        2015-02-16 09:29 (:0.0)
mquinson pts/8        2015-02-17 11:37 (:0.0)
* Hostname
chaipa
* System information
Linux chaipa 3.16-2-amd64 #1 SMP Debian 3.16.3-2 (2014-09-20) x86_64 GNU/Linux
* CPU info
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 58
model name	: Intel(R) Core(TM) i7-3540M CPU @ 3.00GHz
stepping	: 9
microcode	: 0x16
cpu MHz		: 1231.640
cache size	: 4096 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms
bogomips	: 5986.56
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 58
model name	: Intel(R) Core(TM) i7-3540M CPU @ 3.00GHz
stepping	: 9
microcode	: 0x16
cpu MHz		: 1340.859
cache size	: 4096 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 2
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms
bogomips	: 5986.56
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 2
vendor_id	: GenuineIntel
cpu family	: 6
model		: 58
model name	: Intel(R) Core(TM) i7-3540M CPU @ 3.00GHz
stepping	: 9
microcode	: 0x16
cpu MHz		: 1335.703
cache size	: 4096 KB
physical id	: 0
siblings	: 4
core id		: 1
cpu cores	: 2
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms
bogomips	: 5986.56
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 58
model name	: Intel(R) Core(TM) i7-3540M CPU @ 3.00GHz
stepping	: 9
microcode	: 0x16
cpu MHz		: 1396.171
cache size	: 4096 KB
physical id	: 0
siblings	: 4
core id		: 1
cpu cores	: 2
apicid		: 3
initial apicid	: 3
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms
bogomips	: 5986.56
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

* CPU governor
powersave
* CPU frequency
Unknown (information not available)
* Meminfo
MemTotal:       16401544 kB
MemFree:        10948720 kB
MemAvailable:   11377320 kB
Buffers:          118280 kB
Cached:           570724 kB
SwapCached:            0 kB
Active:          4903396 kB
Inactive:         296964 kB
Active(anon):    4538464 kB
Inactive(anon):    94304 kB
Active(file):     364932 kB
Inactive(file):   202660 kB
Unevictable:         144 kB
Mlocked:             144 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:                16 kB
Writeback:             0 kB
AnonPages:       4511464 kB
Mapped:           200584 kB
Shmem:            121412 kB
Slab:             105736 kB
SReclaimable:      59904 kB
SUnreclaim:        45832 kB
KernelStack:        9888 kB
PageTables:        50312 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     8200772 kB
Committed_AS:    8368184 kB
VmallocTotal:   34359738367 kB
VmallocUsed:      317176 kB
VmallocChunk:   34359347464 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:       96204 kB
DirectMap2M:    16611328 kB
* Memory hierarchy
./simgrid_hostinfo.sh: ligne 35: lstopo : commande introuvable
* Environment Variables
XDG_VTNR=7
SSH_AGENT_PID=2240
XDG_SESSION_ID=3
GPG_AGENT_INFO=/tmp/gpg-UaPWyh/S.gpg-agent:2261:1
GLADE_PIXMAP_PATH=:
GRAS_ROOT=/opt/simgrid
TERM=xterm
SHELL=/bin/bash
XDG_MENU_PREFIX=xfce-
VALGRIND_OPTS=--leak-check=yes --leak-resolution=high --num-callers=40 --tool=memcheck --suppressions=/home/mquinson/.valgrind.supp
WINDOWID=58720260
USER=mquinson
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:
LD_LIBRARY_PATH=/opt/simgrid/lib
DEBEMAIL=mquinson@debian.org
GLADE_MODULE_PATH=:
SSH_AUTH_SOCK=/tmp/ssh-fwh1WqsBN88i/agent.2198
SESSION_MANAGER=local/chaipa:@/tmp/.ICE-unix/2254,unix/chaipa:/tmp/.ICE-unix/2254
USERNAME=mquinson
DEB_BUILD_OPTIONS=parallel=4
XDG_CONFIG_DIRS=/etc/xdg
PATH=/home/mquinson/install-3.12/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/mquinson/SCRIPTS:/usr/sbin:/sbin:/opt/simgrid/bin
DESKTOP_SESSION=xfce
PWD=/home/mquinson/Documents/CALLS/infra-songs/WP4/TPDS15/xp
EDITOR=jed
LANG=fr_FR.UTF-8
GDMSESSION=xfce
HISTCONTROL=ignoreboth
GPG_TTY=/dev/pts/8
SHLVL=3
XDG_SEAT=seat0
HOME=/home/mquinson
XDG_SESSION_DESKTOP=xfce
LOGNAME=mquinson
XDG_DATA_DIRS=/usr/share/xfce4:/usr/local/share/:/usr/share/:/usr/share
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-p60sAMaRGt,guid=3d800b6457ae9442302dd2dd54d109c6
DEBFULLNAME=Martin Quinson
WINDOWPATH=7
XDG_RUNTIME_DIR=/run/user/1000
DISPLAY=:0.0
GLADE_CATALOG_PATH=:
XDG_CURRENT_DESKTOP=XFCE
COLORTERM=xfce4-terminal
XAUTHORITY=/var/run/gdm3/auth-for-mquinson-orkW3I/database
_=/usr/bin/printenv
* Tools Versions
** SimGrid Full Version
SimGrid version 3.12-devel
Copyright (c) 2004-2014. The Simgrid Team.
Release build at commit 491af46 (2015-02-16 15:31:17 +0100)
** SimGrid Commit Hash
491af463998597b43a8b9c68c126f97f0089ab5e
** Linux and gcc versions
Linux version 3.16-2-amd64 (debian-kernel@lists.debian.org) (gcc version 4.8.3 (Debian 4.8.3-11) ) #1 SMP Debian 3.16.3-2 (2014-09-20)
** Gcc info
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.9/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 4.9.1-19' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --with-arch-32=i586 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.9.1 (Debian 4.9.1-19) 
** Make tool
GNU Make 4.0
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
** CMake
cmake version 3.0.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
* Compilation result
* Platform file
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid.dtd">
<platform version="3">


<config id="General">
  <prop id="workstation/model" value="compound"/>
  <prop id="network/model" value="SMPI"/>
  <prop id="network/TCP_gamma" value="4194304"/>
  <prop id="network/sender_gap" value="0"/>
  <prop id="maxmin/precision" value="1e-9"/>
  <prop id="smpi/async_small_thres" value="65536"/>
  <prop id="smpi/send_is_detached_thres" value="327680"/>
<!--  <prop id="smpi/os" value="1:8.75118726019245e-06:7.09598480584951e-10;1420:1.38989305424406e-05:2.18111838119125e-10;65536:0.000193970854779561:-4.82025737428887e-11;327680:0:0"/>-->
<!--  <prop id="smpi/or" value="1:9.3069771137911e-06:7.92179414036391e-10;1420:1.43097562292319e-05:8.66975835499791e-10;10000:1.41659209904282e-05:1.00877300603447e-09;65536:0:0"/>-->
<!--  <prop id="smpi/bw_factor" value="0:0.408465938;1420:0.913760459;65536:0.937794396"/>-->
<!--  <prop id="smpi/lat_factor" value="0:1.01;1420:4.02;65536:9.77"/>-->
<!--  -->
 <prop id="smpi/os" value="0:8.9300920419081e-06:7.65438202550106e-10;1420:1.39684254077781e-05:2.97409403415968e-10;32768:1.54082820250394e-05:2.44104034252286e-10;65536:0.000237866424242424:0;327680:0:0"/>
 <prop id="smpi/or" value="0:8.14025462333494e-06:8.3958813204998e-10;1420:1.26995184134793e-05:9.09218191293861e-10;32768:3.09570602567453e-05:6.95645307772806e-10;65536:0:0;327680:0:0"/>
 <prop id="smpi/bw_factor" value="0:0.400976530736138;1420:0.913555534273577;32768:1.07831886657594;65536:0.956083935262915;327680:0.929867998857892"/>
 <prop id="smpi/lat_factor" value="0:1.35489260823384;1420:3.43725032107889;32768:5.72164710873587;65536:11.9885319715471;327680:9.65041953605594"/>  
</config>
 
<AS id="AS_graphene" routing="Full" >
  <cluster id="AS_sgraphene1" prefix="graphene-" suffix=".nancy.grid5000.fr"
           radical="1-256" power="4.18E9" core="4" bw="1.25E8" lat="2.4E-5"
           sharing_policy="FULLDUPLEX" limiter_link="1.875E8" loopback_lat="1.5E-9" loopback_bw="6000000000"></cluster>
  <cluster id="AS_sgraphene2" prefix="graphene-" suffix=".nancy.grid5000.fr"
           radical="257-512" power="4.18E9" core="4" bw="1.25E8" lat="2.4E-5"
           sharing_policy="FULLDUPLEX" limiter_link="1.875E8" loopback_lat="1.5E-9" loopback_bw="6000000000"></cluster>
  <cluster id="AS_sgraphene3" prefix="graphene-" suffix=".nancy.grid5000.fr"
           radical="513-784" power="4.18E9" core="4" bw="1.25E8" lat="2.4E-5"
           sharing_policy="FULLDUPLEX" limiter_link="1.875E8" loopback_lat="1.5E-9" loopback_bw="6000000000"></cluster>
  <cluster id="AS_sgraphene4" prefix="graphene-" suffix=".nancy.grid5000.fr"
           radical="785-1024" power="4.18E9" core="4" bw="1.25E8" lat="2.4E-5"
           sharing_policy="FULLDUPLEX" limiter_link="1.875E8" loopback_lat="1.5E-9" loopback_bw="6000000000"></cluster>

  <link id="switch-backbone1" bandwidth="1162500000" latency="1.5E-6" sharing_policy="FULLDUPLEX"/>
  <link id="explicit-limiter1" bandwidth="1511250000" latency="0" sharing_policy="SHARED"/>

  <link id="switch-backbone2" bandwidth="1162500000" latency="1.5E-6" sharing_policy="FULLDUPLEX"/>
  <link id="explicit-limiter2" bandwidth="1511250000" latency="0" sharing_policy="SHARED"/>

  <link id="switch-backbone3" bandwidth="1162500000" latency="1.5E-6" sharing_policy="FULLDUPLEX"/>
  <link id="explicit-limiter3" bandwidth="1511250000" latency="0" sharing_policy="SHARED"/>

  <link id="switch-backbone4" bandwidth="1162500000" latency="1.5E-6" sharing_policy="FULLDUPLEX"/>
  <link id="explicit-limiter4" bandwidth="1511250000" latency="0" sharing_policy="SHARED"/>


     <ASroute src="AS_sgraphene1" dst="AS_sgraphene2"
         gw_src="graphene-AS_sgraphene1_router.nancy.grid5000.fr"
         gw_dst="graphene-AS_sgraphene2_router.nancy.grid5000.fr"
         symmetrical="NO"
         >
                <link_ctn id="switch-backbone1" direction="UP"/>
                <link_ctn id="explicit-limiter1"/>
                <link_ctn id="explicit-limiter2"/>
                <link_ctn id="switch-backbone2" direction="DOWN"/>
                
     </ASroute>
     <ASroute src="AS_sgraphene2" dst="AS_sgraphene1"
         gw_src="graphene-AS_sgraphene2_router.nancy.grid5000.fr"
         gw_dst="graphene-AS_sgraphene1_router.nancy.grid5000.fr"
         symmetrical="NO"
         >
                <link_ctn id="switch-backbone2" direction="UP"/>
                <link_ctn id="explicit-limiter2"/>
                <link_ctn id="explicit-limiter1"/>
                <link_ctn id="switch-backbone1" direction="DOWN"/>
     </ASroute>
     <ASroute src="AS_sgraphene2" dst="AS_sgraphene3"
         gw_src="graphene-AS_sgraphene2_router.nancy.grid5000.fr"
         gw_dst="graphene-AS_sgraphene3_router.nancy.grid5000.fr"
          symmetrical="NO"
         >
                <link_ctn id="switch-backbone2" direction="UP"/>                
                <link_ctn id="explicit-limiter2"/>
                <link_ctn id="explicit-limiter3"/>
                <link_ctn id="switch-backbone3" direction="DOWN"/>
     </ASroute>
     <ASroute src="AS_sgraphene1" dst="AS_sgraphene3"
         gw_src="graphene-AS_sgraphene1_router.nancy.grid5000.fr"
         gw_dst="graphene-AS_sgraphene3_router.nancy.grid5000.fr"
         symmetrical="NO"         
         >
                <link_ctn id="switch-backbone1" direction="UP"/>
                <link_ctn id="explicit-limiter1"/>
                <link_ctn id="explicit-limiter3"/>
                <link_ctn id="switch-backbone3" direction="DOWN"/>
     </ASroute>
          <ASroute src="AS_sgraphene3" dst="AS_sgraphene1"
         gw_src="graphene-AS_sgraphene3_router.nancy.grid5000.fr"
         gw_dst="graphene-AS_sgraphene1_router.nancy.grid5000.fr"
         symmetrical="NO"         
         >
                <link_ctn id="switch-backbone3" direction="UP"/>
                <link_ctn id="explicit-limiter3"/>
                <link_ctn id="explicit-limiter1"/>
                <link_ctn id="switch-backbone1" direction="DOWN"/>
     </ASroute>
     
          <ASroute src="AS_sgraphene1" dst="AS_sgraphene4"
         gw_src="graphene-AS_sgraphene1_router.nancy.grid5000.fr"
         gw_dst="graphene-AS_sgraphene4_router.nancy.grid5000.fr"
         symmetrical="NO"         
         >
                <link_ctn id="switch-backbone1" direction="UP"/>
                <link_ctn id="explicit-limiter1"/>
                <link_ctn id="explicit-limiter4"/>
                <link_ctn id="switch-backbone4" direction="DOWN"/>
     </ASroute>
               <ASroute src="AS_sgraphene4" dst="AS_sgraphene1"
         gw_src="graphene-AS_sgraphene4_router.nancy.grid5000.fr"
         gw_dst="graphene-AS_sgraphene1_router.nancy.grid5000.fr"
         symmetrical="NO"         
         >
                <link_ctn id="switch-backbone4" direction="UP"/>
                <link_ctn id="explicit-limiter4"/>
                <link_ctn id="explicit-limiter1"/>
                <link_ctn id="switch-backbone1" direction="DOWN"/>
     </ASroute>
          <ASroute src="AS_sgraphene2" dst="AS_sgraphene4"
         gw_src="graphene-AS_sgraphene2_router.nancy.grid5000.fr"
         gw_dst="graphene-AS_sgraphene4_router.nancy.grid5000.fr"
         symmetrical="NO"         
         >
                <link_ctn id="switch-backbone2" direction="UP"/>
                <link_ctn id="explicit-limiter2"/>
                <link_ctn id="explicit-limiter4"/>
                <link_ctn id="switch-backbone4" direction="DOWN"/>
     </ASroute>
          <ASroute src="AS_sgraphene3" dst="AS_sgraphene4"
         gw_src="graphene-AS_sgraphene3_router.nancy.grid5000.fr"
         gw_dst="graphene-AS_sgraphene4_router.nancy.grid5000.fr"
         symmetrical="NO"         
         >
                <link_ctn id="switch-backbone3" direction="UP"/>
                <link_ctn id="explicit-limiter3"/>
                <link_ctn id="explicit-limiter4"/>
                <link_ctn id="switch-backbone4" direction="DOWN"/>
     </ASroute>
              <ASroute src="AS_sgraphene4" dst="AS_sgraphene3"
         gw_src="graphene-AS_sgraphene4_router.nancy.grid5000.fr"
         gw_dst="graphene-AS_sgraphene3_router.nancy.grid5000.fr"
         symmetrical="NO"         
         >
                <link_ctn id="switch-backbone4" direction="UP"/>
                <link_ctn id="explicit-limiter4"/>
                <link_ctn id="explicit-limiter3"/>
                <link_ctn id="switch-backbone3" direction="DOWN"/>
     </ASroute>
     
               <ASroute src="AS_sgraphene3" dst="AS_sgraphene2"
         gw_src="graphene-AS_sgraphene3_router.nancy.grid5000.fr"
         gw_dst="graphene-AS_sgraphene2_router.nancy.grid5000.fr"
         symmetrical="NO"         
         >
                <link_ctn id="switch-backbone3" direction="UP"/>
                <link_ctn id="explicit-limiter3"/>
                <link_ctn id="explicit-limiter2"/>
                <link_ctn id="switch-backbone2" direction="DOWN"/>
     </ASroute>
     
                    <ASroute src="AS_sgraphene4" dst="AS_sgraphene2"
         gw_src="graphene-AS_sgraphene4_router.nancy.grid5000.fr"
         gw_dst="graphene-AS_sgraphene2_router.nancy.grid5000.fr"
         symmetrical="NO"         
         >
                <link_ctn id="switch-backbone4" direction="UP"/>
                <link_ctn id="explicit-limiter4"/>
                <link_ctn id="explicit-limiter2"/>
                <link_ctn id="switch-backbone2" direction="DOWN"/>
     </ASroute>
 </AS>
</platform>

* Experiment 1
Do proc:413 size:2121871 freemem:10926804k mem usage:1752665446
** Test with algorithm 2dmesh
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 413 ./alltoall 2121871 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:2dmesh
*** raw stdout

*** raw stderr
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/TCP_gamma' to '4194304'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/running_power' to '20000'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/alltoall' to '2dmesh'
  [0.000000] [smpi_coll/INFO] Switch to algorithm 2dmesh for collective alltoall
  [0.000000] [smpi_coll/INFO] Switch to algorithm 2dmesh for collective alltoall
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/bw_factor' to '0:0.400976530736138;1420:0.913555534273577;32768:1.07831886657594;65536:0.956083935262915;327680:0.929867998857892'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/TCP_gamma' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'maxmin/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/or' to '0:8.14025462333494e-06:8.3958813204998e-10;1420:1.26995184134793e-05:9.09218191293861e-10;32768:3.09570602567453e-05:6.95645307772806e-10;65536:0:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/os' to '0:8.9300920419081e-06:7.65438202550106e-10;1420:1.39684254077781e-05:2.97409403415968e-10;32768:1.54082820250394e-05:2.44104034252286e-10;65536:0.000237866424242424:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/sender_gap' to '0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/send_is_detached_thres' to '327680'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'workstation/model' to 'compound'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/model' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/async_small_thres' to '65536'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/lat_factor' to '0:1.35489260823384;1420:3.43725032107889;32768:5.72164710873587;65536:11.9885319715471;327680:9.65041953605594'
  [0.000000] /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:131: [simix_deployment/ERROR] Unrecoverable error at tmpVQcOzD:8. The full exception stack follows, in case it helps you to diagnose the problem.
  ** SimGrid: UNCAUGHT EXCEPTION received on ./alltoall(0): category: invalid argument; value: 0
  ** Host 'node-0.acme.org' unknown
  ** Thrown by () in this process
  [0.000000] /home/mquinson/Code/simgrid/src/xbt/ex.c:146: [xbt_ex/CRITICAL] Host 'node-0.acme.org' unknown
  
  **   In parse_process() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:28
  **   In sg_platf_new_process() at /home/mquinson/Code/simgrid/src/surf/sg_platf.c:264 (discriminator 3)
  **   In ETag_surfxml_process() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:960
  **   In surf_parse_lex() at /home/mquinson/Code/simgrid/src/surf/simgrid_dtd.c:9228
  **   In _surf_parse() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:1066
  **   In SIMIX_launch_application() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:125
  **   In smpi_main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:661
  **   In main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:520
  Aborted

*** raw timing information
Command exited with non-zero status 134
clock:0.64 user:0.07 sys:0.10 swapped:0 exitval:134 max:18928k

*** Result
FAILED_RESULT: non-zero status (algo:2dmesh numproc:413 msgsize:2121871 hostTime:0.64 hostMem:18928k)
** Test with algorithm 3dmesh
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 413 ./alltoall 2121871 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:3dmesh
*** raw stdout

*** raw stderr
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/TCP_gamma' to '4194304'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/running_power' to '20000'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/alltoall' to '3dmesh'
  [0.000000] [smpi_coll/INFO] Switch to algorithm 3dmesh for collective alltoall
  [0.000000] [smpi_coll/INFO] Switch to algorithm 3dmesh for collective alltoall
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/bw_factor' to '0:0.400976530736138;1420:0.913555534273577;32768:1.07831886657594;65536:0.956083935262915;327680:0.929867998857892'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/TCP_gamma' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'maxmin/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/or' to '0:8.14025462333494e-06:8.3958813204998e-10;1420:1.26995184134793e-05:9.09218191293861e-10;32768:3.09570602567453e-05:6.95645307772806e-10;65536:0:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/os' to '0:8.9300920419081e-06:7.65438202550106e-10;1420:1.39684254077781e-05:2.97409403415968e-10;32768:1.54082820250394e-05:2.44104034252286e-10;65536:0.000237866424242424:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/sender_gap' to '0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/send_is_detached_thres' to '327680'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'workstation/model' to 'compound'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/model' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/async_small_thres' to '65536'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/lat_factor' to '0:1.35489260823384;1420:3.43725032107889;32768:5.72164710873587;65536:11.9885319715471;327680:9.65041953605594'
  [0.000000] /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:131: [simix_deployment/ERROR] Unrecoverable error at tmp9CrgMT:8. The full exception stack follows, in case it helps you to diagnose the problem.
  ** SimGrid: UNCAUGHT EXCEPTION received on ./alltoall(0): category: invalid argument; value: 0
  ** Host 'node-0.acme.org' unknown
  ** Thrown by () in this process
  [0.000000] /home/mquinson/Code/simgrid/src/xbt/ex.c:146: [xbt_ex/CRITICAL] Host 'node-0.acme.org' unknown
  
  **   In parse_process() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:28
  **   In sg_platf_new_process() at /home/mquinson/Code/simgrid/src/surf/sg_platf.c:264 (discriminator 3)
  **   In ETag_surfxml_process() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:960
  **   In surf_parse_lex() at /home/mquinson/Code/simgrid/src/surf/simgrid_dtd.c:9228
  **   In _surf_parse() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:1066
  **   In SIMIX_launch_application() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:125
  **   In smpi_main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:661
  **   In main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:520
  Aborted

*** raw timing information
Command exited with non-zero status 134
clock:0.58 user:0.08 sys:0.08 swapped:0 exitval:134 max:18788k

*** Result
FAILED_RESULT: non-zero status (algo:3dmesh numproc:413 msgsize:2121871 hostTime:0.58 hostMem:18788k)
** Test with algorithm basic_linear
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 413 ./alltoall 2121871 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:basic_linear
*** raw stdout

*** raw stderr
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/TCP_gamma' to '4194304'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/running_power' to '20000'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/alltoall' to 'basic_linear'
  [0.000000] [smpi_coll/INFO] Switch to algorithm basic_linear for collective alltoall
  [0.000000] [smpi_coll/INFO] Switch to algorithm basic_linear for collective alltoall
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/bw_factor' to '0:0.400976530736138;1420:0.913555534273577;32768:1.07831886657594;65536:0.956083935262915;327680:0.929867998857892'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/TCP_gamma' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'maxmin/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/or' to '0:8.14025462333494e-06:8.3958813204998e-10;1420:1.26995184134793e-05:9.09218191293861e-10;32768:3.09570602567453e-05:6.95645307772806e-10;65536:0:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/os' to '0:8.9300920419081e-06:7.65438202550106e-10;1420:1.39684254077781e-05:2.97409403415968e-10;32768:1.54082820250394e-05:2.44104034252286e-10;65536:0.000237866424242424:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/sender_gap' to '0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/send_is_detached_thres' to '327680'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'workstation/model' to 'compound'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/model' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/async_small_thres' to '65536'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/lat_factor' to '0:1.35489260823384;1420:3.43725032107889;32768:5.72164710873587;65536:11.9885319715471;327680:9.65041953605594'
  [0.000000] /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:131: [simix_deployment/ERROR] Unrecoverable error at tmp22gDZk:8. The full exception stack follows, in case it helps you to diagnose the problem.
  ** SimGrid: UNCAUGHT EXCEPTION received on ./alltoall(0): category: invalid argument; value: 0
  ** Host 'node-0.acme.org' unknown
  ** Thrown by () in this process
  [0.000000] /home/mquinson/Code/simgrid/src/xbt/ex.c:146: [xbt_ex/CRITICAL] Host 'node-0.acme.org' unknown
  
  **   In parse_process() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:28
  **   In sg_platf_new_process() at /home/mquinson/Code/simgrid/src/surf/sg_platf.c:264 (discriminator 3)
  **   In ETag_surfxml_process() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:960
  **   In surf_parse_lex() at /home/mquinson/Code/simgrid/src/surf/simgrid_dtd.c:9228
  **   In _surf_parse() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:1066
  **   In SIMIX_launch_application() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:125
  **   In smpi_main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:661
  **   In main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:520
  Aborted

*** raw timing information
Command exited with non-zero status 134
clock:0.55 user:0.06 sys:0.07 swapped:0 exitval:134 max:18776k

*** Result
FAILED_RESULT: non-zero status (algo:basic_linear numproc:413 msgsize:2121871 hostTime:0.55 hostMem:18776k)
** Test with algorithm bruck
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 413 ./alltoall 2121871 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:bruck
*** raw stdout

*** raw stderr
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/TCP_gamma' to '4194304'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/running_power' to '20000'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/alltoall' to 'bruck'
  [0.000000] [smpi_coll/INFO] Switch to algorithm bruck for collective alltoall
  [0.000000] [smpi_coll/INFO] Switch to algorithm bruck for collective alltoall
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/bw_factor' to '0:0.400976530736138;1420:0.913555534273577;32768:1.07831886657594;65536:0.956083935262915;327680:0.929867998857892'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/TCP_gamma' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'maxmin/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/or' to '0:8.14025462333494e-06:8.3958813204998e-10;1420:1.26995184134793e-05:9.09218191293861e-10;32768:3.09570602567453e-05:6.95645307772806e-10;65536:0:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/os' to '0:8.9300920419081e-06:7.65438202550106e-10;1420:1.39684254077781e-05:2.97409403415968e-10;32768:1.54082820250394e-05:2.44104034252286e-10;65536:0.000237866424242424:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/sender_gap' to '0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/send_is_detached_thres' to '327680'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'workstation/model' to 'compound'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/model' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/async_small_thres' to '65536'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/lat_factor' to '0:1.35489260823384;1420:3.43725032107889;32768:5.72164710873587;65536:11.9885319715471;327680:9.65041953605594'
  [0.000000] /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:131: [simix_deployment/ERROR] Unrecoverable error at tmpOkX48h:8. The full exception stack follows, in case it helps you to diagnose the problem.
  ** SimGrid: UNCAUGHT EXCEPTION received on ./alltoall(0): category: invalid argument; value: 0
  ** Host 'node-0.acme.org' unknown
  ** Thrown by () in this process
  [0.000000] /home/mquinson/Code/simgrid/src/xbt/ex.c:146: [xbt_ex/CRITICAL] Host 'node-0.acme.org' unknown
  
  **   In parse_process() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:28
  **   In sg_platf_new_process() at /home/mquinson/Code/simgrid/src/surf/sg_platf.c:264 (discriminator 3)
  **   In ETag_surfxml_process() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:960
  **   In surf_parse_lex() at /home/mquinson/Code/simgrid/src/surf/simgrid_dtd.c:9228
  **   In _surf_parse() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:1066
  **   In SIMIX_launch_application() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:125
  **   In smpi_main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:661
  **   In main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:520
  Aborted

*** raw timing information
Command exited with non-zero status 134
clock:0.61 user:0.08 sys:0.09 swapped:0 exitval:134 max:18932k

*** Result
FAILED_RESULT: non-zero status (algo:bruck numproc:413 msgsize:2121871 hostTime:0.61 hostMem:18932k)
** Test with algorithm pair
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 413 ./alltoall 2121871 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:pair
*** raw stdout

*** raw stderr
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/TCP_gamma' to '4194304'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/running_power' to '20000'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/alltoall' to 'pair'
  [0.000000] [smpi_coll/INFO] Switch to algorithm pair for collective alltoall
  [0.000000] [smpi_coll/INFO] Switch to algorithm pair for collective alltoall
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/bw_factor' to '0:0.400976530736138;1420:0.913555534273577;32768:1.07831886657594;65536:0.956083935262915;327680:0.929867998857892'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/TCP_gamma' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'maxmin/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/or' to '0:8.14025462333494e-06:8.3958813204998e-10;1420:1.26995184134793e-05:9.09218191293861e-10;32768:3.09570602567453e-05:6.95645307772806e-10;65536:0:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/os' to '0:8.9300920419081e-06:7.65438202550106e-10;1420:1.39684254077781e-05:2.97409403415968e-10;32768:1.54082820250394e-05:2.44104034252286e-10;65536:0.000237866424242424:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/sender_gap' to '0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/send_is_detached_thres' to '327680'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'workstation/model' to 'compound'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/model' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/async_small_thres' to '65536'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/lat_factor' to '0:1.35489260823384;1420:3.43725032107889;32768:5.72164710873587;65536:11.9885319715471;327680:9.65041953605594'
  [0.000000] /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:131: [simix_deployment/ERROR] Unrecoverable error at tmpSoZYqY:8. The full exception stack follows, in case it helps you to diagnose the problem.
  ** SimGrid: UNCAUGHT EXCEPTION received on ./alltoall(0): category: invalid argument; value: 0
  ** Host 'node-0.acme.org' unknown
  ** Thrown by () in this process
  [0.000000] /home/mquinson/Code/simgrid/src/xbt/ex.c:146: [xbt_ex/CRITICAL] Host 'node-0.acme.org' unknown
  
  **   In parse_process() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:28
  **   In sg_platf_new_process() at /home/mquinson/Code/simgrid/src/surf/sg_platf.c:264 (discriminator 3)
  **   In ETag_surfxml_process() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:960
  **   In surf_parse_lex() at /home/mquinson/Code/simgrid/src/surf/simgrid_dtd.c:9228
  **   In _surf_parse() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:1066
  **   In SIMIX_launch_application() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:125
  **   In smpi_main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:661
  **   In main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:520
  Aborted

*** raw timing information
Command exited with non-zero status 134
clock:0.57 user:0.06 sys:0.08 swapped:0 exitval:134 max:18684k

*** Result
FAILED_RESULT: non-zero status (algo:pair numproc:413 msgsize:2121871 hostTime:0.57 hostMem:18684k)
** Test with algorithm pair_rma
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 413 ./alltoall 2121871 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:pair_rma
*** raw stdout

*** raw stderr
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/TCP_gamma' to '4194304'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/running_power' to '20000'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/alltoall' to 'pair_rma'
  [0.000000] [smpi_coll/INFO] Switch to algorithm pair_rma for collective alltoall
  [0.000000] [smpi_coll/INFO] Switch to algorithm pair_rma for collective alltoall
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/bw_factor' to '0:0.400976530736138;1420:0.913555534273577;32768:1.07831886657594;65536:0.956083935262915;327680:0.929867998857892'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/TCP_gamma' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'maxmin/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/or' to '0:8.14025462333494e-06:8.3958813204998e-10;1420:1.26995184134793e-05:9.09218191293861e-10;32768:3.09570602567453e-05:6.95645307772806e-10;65536:0:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/os' to '0:8.9300920419081e-06:7.65438202550106e-10;1420:1.39684254077781e-05:2.97409403415968e-10;32768:1.54082820250394e-05:2.44104034252286e-10;65536:0.000237866424242424:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/sender_gap' to '0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/send_is_detached_thres' to '327680'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'workstation/model' to 'compound'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/model' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/async_small_thres' to '65536'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/lat_factor' to '0:1.35489260823384;1420:3.43725032107889;32768:5.72164710873587;65536:11.9885319715471;327680:9.65041953605594'
  [0.000000] /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:131: [simix_deployment/ERROR] Unrecoverable error at tmpfhkjec:8. The full exception stack follows, in case it helps you to diagnose the problem.
  ** SimGrid: UNCAUGHT EXCEPTION received on ./alltoall(0): category: invalid argument; value: 0
  ** Host 'node-0.acme.org' unknown
  ** Thrown by () in this process
  [0.000000] /home/mquinson/Code/simgrid/src/xbt/ex.c:146: [xbt_ex/CRITICAL] Host 'node-0.acme.org' unknown
  
  **   In parse_process() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:28
  **   In sg_platf_new_process() at /home/mquinson/Code/simgrid/src/surf/sg_platf.c:264 (discriminator 3)
  **   In ETag_surfxml_process() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:960
  **   In surf_parse_lex() at /home/mquinson/Code/simgrid/src/surf/simgrid_dtd.c:9228
  **   In _surf_parse() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:1066
  **   In SIMIX_launch_application() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:125
  **   In smpi_main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:661
  **   In main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:520
  Aborted

*** raw timing information
Command exited with non-zero status 134
clock:0.56 user:0.07 sys:0.06 swapped:0 exitval:134 max:18792k

*** Result
FAILED_RESULT: non-zero status (algo:pair_rma numproc:413 msgsize:2121871 hostTime:0.56 hostMem:18792k)
** Test with algorithm pair_light_barrier
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 413 ./alltoall 2121871 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:pair_light_barrier
*** raw stdout

*** raw stderr
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/TCP_gamma' to '4194304'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/running_power' to '20000'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/alltoall' to 'pair_light_barrier'
  [0.000000] [smpi_coll/INFO] Switch to algorithm pair_light_barrier for collective alltoall
  [0.000000] [smpi_coll/INFO] Switch to algorithm pair_light_barrier for collective alltoall
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/bw_factor' to '0:0.400976530736138;1420:0.913555534273577;32768:1.07831886657594;65536:0.956083935262915;327680:0.929867998857892'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/TCP_gamma' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'maxmin/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/or' to '0:8.14025462333494e-06:8.3958813204998e-10;1420:1.26995184134793e-05:9.09218191293861e-10;32768:3.09570602567453e-05:6.95645307772806e-10;65536:0:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/os' to '0:8.9300920419081e-06:7.65438202550106e-10;1420:1.39684254077781e-05:2.97409403415968e-10;32768:1.54082820250394e-05:2.44104034252286e-10;65536:0.000237866424242424:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/sender_gap' to '0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/send_is_detached_thres' to '327680'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'workstation/model' to 'compound'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/model' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/async_small_thres' to '65536'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/lat_factor' to '0:1.35489260823384;1420:3.43725032107889;32768:5.72164710873587;65536:11.9885319715471;327680:9.65041953605594'
  [0.000000] /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:131: [simix_deployment/ERROR] Unrecoverable error at tmphLsNWR:8. The full exception stack follows, in case it helps you to diagnose the problem.
  ** SimGrid: UNCAUGHT EXCEPTION received on ./alltoall(0): category: invalid argument; value: 0
  ** Host 'node-0.acme.org' unknown
  ** Thrown by () in this process
  [0.000000] /home/mquinson/Code/simgrid/src/xbt/ex.c:146: [xbt_ex/CRITICAL] Host 'node-0.acme.org' unknown
  
  **   In parse_process() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:28
  **   In sg_platf_new_process() at /home/mquinson/Code/simgrid/src/surf/sg_platf.c:264 (discriminator 3)
  **   In ETag_surfxml_process() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:960
  **   In surf_parse_lex() at /home/mquinson/Code/simgrid/src/surf/simgrid_dtd.c:9228
  **   In _surf_parse() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:1066
  **   In SIMIX_launch_application() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:125
  **   In smpi_main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:661
  **   In main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:520
  Aborted

*** raw timing information
Command exited with non-zero status 134
clock:0.56 user:0.06 sys:0.07 swapped:0 exitval:134 max:18920k

*** Result
FAILED_RESULT: non-zero status (algo:pair_light_barrier numproc:413 msgsize:2121871 hostTime:0.56 hostMem:18920k)
** Test with algorithm pair_mpi_barrier
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 413 ./alltoall 2121871 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:pair_mpi_barrier
*** raw stdout

*** raw stderr
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/TCP_gamma' to '4194304'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/running_power' to '20000'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/alltoall' to 'pair_mpi_barrier'
  [0.000000] [smpi_coll/INFO] Switch to algorithm pair_mpi_barrier for collective alltoall
  [0.000000] [smpi_coll/INFO] Switch to algorithm pair_mpi_barrier for collective alltoall
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/bw_factor' to '0:0.400976530736138;1420:0.913555534273577;32768:1.07831886657594;65536:0.956083935262915;327680:0.929867998857892'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/TCP_gamma' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'maxmin/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/or' to '0:8.14025462333494e-06:8.3958813204998e-10;1420:1.26995184134793e-05:9.09218191293861e-10;32768:3.09570602567453e-05:6.95645307772806e-10;65536:0:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/os' to '0:8.9300920419081e-06:7.65438202550106e-10;1420:1.39684254077781e-05:2.97409403415968e-10;32768:1.54082820250394e-05:2.44104034252286e-10;65536:0.000237866424242424:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/sender_gap' to '0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/send_is_detached_thres' to '327680'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'workstation/model' to 'compound'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/model' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/async_small_thres' to '65536'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/lat_factor' to '0:1.35489260823384;1420:3.43725032107889;32768:5.72164710873587;65536:11.9885319715471;327680:9.65041953605594'
  [0.000000] /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:131: [simix_deployment/ERROR] Unrecoverable error at tmpjMyNVe:8. The full exception stack follows, in case it helps you to diagnose the problem.
  ** SimGrid: UNCAUGHT EXCEPTION received on ./alltoall(0): category: invalid argument; value: 0
  ** Host 'node-0.acme.org' unknown
  ** Thrown by () in this process
  [0.000000] /home/mquinson/Code/simgrid/src/xbt/ex.c:146: [xbt_ex/CRITICAL] Host 'node-0.acme.org' unknown
  
  **   In parse_process() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:28
  **   In sg_platf_new_process() at /home/mquinson/Code/simgrid/src/surf/sg_platf.c:264 (discriminator 3)
  **   In ETag_surfxml_process() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:960
  **   In surf_parse_lex() at /home/mquinson/Code/simgrid/src/surf/simgrid_dtd.c:9228
  **   In _surf_parse() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:1066
  **   In SIMIX_launch_application() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:125
  **   In smpi_main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:661
  **   In main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:520
  Aborted

*** raw timing information
Command exited with non-zero status 134
clock:0.56 user:0.08 sys:0.06 swapped:0 exitval:134 max:18924k

*** Result
FAILED_RESULT: non-zero status (algo:pair_mpi_barrier numproc:413 msgsize:2121871 hostTime:0.56 hostMem:18924k)
** Test with algorithm pair_one_barrier
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 413 ./alltoall 2121871 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:pair_one_barrier
*** raw stdout

*** raw stderr

*** raw timing information
Command terminated by signal 2
clock:0.39 user:0.01 sys:0.03 swapped:0 exitval:0 max:2348k

*** Result
FAILED_RESULT: signal detected (algo:pair_one_barrier numproc:413 msgsize:2121871 hostTime:0.39 hostMem:2348k)
** Test with algorithm rdb
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 413 ./alltoall 2121871 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:rdb
*** raw stdout

*** raw stderr
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/TCP_gamma' to '4194304'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/running_power' to '20000'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/alltoall' to 'rdb'
  [0.000000] [smpi_coll/INFO] Switch to algorithm rdb for collective alltoall
  [0.000000] [smpi_coll/INFO] Switch to algorithm rdb for collective alltoall
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/bw_factor' to '0:0.400976530736138;1420:0.913555534273577;32768:1.07831886657594;65536:0.956083935262915;327680:0.929867998857892'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/TCP_gamma' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'maxmin/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/or' to '0:8.14025462333494e-06:8.3958813204998e-10;1420:1.26995184134793e-05:9.09218191293861e-10;32768:3.09570602567453e-05:6.95645307772806e-10;65536:0:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/os' to '0:8.9300920419081e-06:7.65438202550106e-10;1420:1.39684254077781e-05:2.97409403415968e-10;32768:1.54082820250394e-05:2.44104034252286e-10;65536:0.000237866424242424:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/sender_gap' to '0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/send_is_detached_thres' to '327680'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'workstation/model' to 'compound'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/model' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/async_small_thres' to '65536'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/lat_factor' to '0:1.35489260823384;1420:3.43725032107889;32768:5.72164710873587;65536:11.9885319715471;327680:9.65041953605594'
  [0.000000] /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:131: [simix_deployment/ERROR] Unrecoverable error at tmpBjw3kA:8. The full exception stack follows, in case it helps you to diagnose the problem.
  ** SimGrid: UNCAUGHT EXCEPTION received on ./alltoall(0): category: invalid argument; value: 0
  ** Host 'node-0.acme.org' unknown
  ** Thrown by () in this process
  [0.000000] /home/mquinson/Code/simgrid/src/xbt/ex.c:146: [xbt_ex/CRITICAL] Host 'node-0.acme.org' unknown
  [0.000000] [simix_kernel/INFO] CTRL-C pressed. The current status will be displayed before exit (disable that behavior with option 'verbose-exit').
  [0.000000] [simix_kernel/INFO] 0 processes are still running, waiting for something.
  [0.000000] [simix_kernel/INFO] Legend of the following listing: "Process <pid> (<name>@<host>): <status>"

*** raw timing information
Command terminated by signal 2
clock:0.50 user:0.05 sys:0.03 swapped:0 exitval:0 max:13556k

*** Result
FAILED_RESULT: signal detected (algo:rdb numproc:413 msgsize:2121871 hostTime:0.50 hostMem:13556k)
** Test with algorithm ring
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 413 ./alltoall 2121871 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:ring
*** raw stdout

*** raw stderr

*** raw timing information
Command terminated by signal 2
clock:0.03 user:0.00 sys:0.00 swapped:0 exitval:0 max:2376k

*** Result
FAILED_RESULT: signal detected (algo:ring numproc:413 msgsize:2121871 hostTime:0.03 hostMem:2376k)
** Test with algorithm ring_light_barrier
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 413 ./alltoall 2121871 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:ring_light_barrier
*** raw stdout

*** raw stderr

*** raw timing information
Command terminated by signal 2
clock:0.04 user:0.00 sys:0.00 swapped:0 exitval:0 max:2348k

*** Result
FAILED_RESULT: signal detected (algo:ring_light_barrier numproc:413 msgsize:2121871 hostTime:0.04 hostMem:2348k)
** Test with algorithm ring_mpi_barrier
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 413 ./alltoall 2121871 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:ring_mpi_barrier
*** raw stdout

*** raw stderr

*** raw timing information
Command terminated by signal 2
clock:0.04 user:0.00 sys:0.00 swapped:0 exitval:0 max:2472k

*** Result
FAILED_RESULT: signal detected (algo:ring_mpi_barrier numproc:413 msgsize:2121871 hostTime:0.04 hostMem:2472k)
** Test with algorithm ring_one_barrier
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 413 ./alltoall 2121871 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:ring_one_barrier
*** raw stdout

*** raw stderr

*** raw timing information
Command terminated by signal 2
clock:0.04 user:0.00 sys:0.00 swapped:0 exitval:0 max:2380k

*** Result
FAILED_RESULT: signal detected (algo:ring_one_barrier numproc:413 msgsize:2121871 hostTime:0.04 hostMem:2380k)
** Test with algorithm mvapich2_scatter_dest
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 413 ./alltoall 2121871 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:mvapich2_scatter_dest
*** raw stdout

*** raw stderr

*** raw timing information
Command terminated by signal 2
clock:0.04 user:0.00 sys:0.00 swapped:0 exitval:0 max:2316k

*** Result
FAILED_RESULT: signal detected (algo:mvapich2_scatter_dest numproc:413 msgsize:2121871 hostTime:0.04 hostMem:2316k)
** Test with algorithm mvapich2
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 413 ./alltoall 2121871 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:mvapich2
*** raw stdout

*** raw stderr

*** raw timing information
Command terminated by signal 2
clock:0.04 user:0.00 sys:0.00 swapped:0 exitval:0 max:2440k

*** Result
FAILED_RESULT: signal detected (algo:mvapich2 numproc:413 msgsize:2121871 hostTime:0.04 hostMem:2440k)
** Test with algorithm ompi
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 413 ./alltoall 2121871 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:ompi
*** raw stdout

*** raw stderr

*** raw timing information
Command terminated by signal 2
clock:0.04 user:0.00 sys:0.00 swapped:0 exitval:0 max:2376k

*** Result
FAILED_RESULT: signal detected (algo:ompi numproc:413 msgsize:2121871 hostTime:0.04 hostMem:2376k)
** Test with algorithm mpich
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 413 ./alltoall 2121871 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:mpich
*** raw stdout

*** raw stderr

*** raw timing information
Command terminated by signal 2
clock:0.04 user:0.00 sys:0.00 swapped:0 exitval:0 max:2432k

*** Result
FAILED_RESULT: signal detected (algo:mpich numproc:413 msgsize:2121871 hostTime:0.04 hostMem:2432k)
** Test with algorithm impi
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 413 ./alltoall 2121871 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:impi
*** raw stdout

*** raw stderr

*** raw timing information
Command terminated by signal 2
clock:0.04 user:0.00 sys:0.00 swapped:0 exitval:0 max:2400k

*** Result
FAILED_RESULT: signal detected (algo:impi numproc:413 msgsize:2121871 hostTime:0.04 hostMem:2400k)
* Experiment 2
Don't do proc:790 size:10010314 as there is not enough memory (free mem: 10926980 kb)
Do proc:229 size:6650394 freemem:10926980k mem usage:3045880452
** Test with algorithm 2dmesh
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 229 ./alltoall 6650394 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:2dmesh
*** raw stdout

*** raw stderr

*** raw timing information
Command terminated by signal 2
clock:0.03 user:0.00 sys:0.00 swapped:0 exitval:0 max:2380k

*** Result
FAILED_RESULT: signal detected (algo:2dmesh numproc:229 msgsize:6650394 hostTime:0.03 hostMem:2380k)
** Test with algorithm 3dmesh
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 229 ./alltoall 6650394 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:3dmesh
*** raw stdout

*** raw stderr

*** raw timing information
Command terminated by signal 2
clock:0.04 user:0.00 sys:0.00 swapped:0 exitval:0 max:2376k

*** Result
FAILED_RESULT: signal detected (algo:3dmesh numproc:229 msgsize:6650394 hostTime:0.04 hostMem:2376k)
** Test with algorithm basic_linear
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 229 ./alltoall 6650394 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:basic_linear
*** raw stdout

*** raw stderr

*** raw timing information
Command terminated by signal 2
clock:0.04 user:0.00 sys:0.00 swapped:0 exitval:0 max:2484k

*** Result
FAILED_RESULT: signal detected (algo:basic_linear numproc:229 msgsize:6650394 hostTime:0.04 hostMem:2484k)
** Test with algorithm bruck
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 229 ./alltoall 6650394 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:bruck
*** raw stdout

*** raw stderr

*** raw timing information
Command terminated by signal 2
clock:0.04 user:0.00 sys:0.00 swapped:0 exitval:0 max:2460k

*** Result
FAILED_RESULT: signal detected (algo:bruck numproc:229 msgsize:6650394 hostTime:0.04 hostMem:2460k)
** Test with algorithm pair
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 229 ./alltoall 6650394 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:pair
*** raw stdout

*** raw stderr

*** raw timing information
Command terminated by signal 2
clock:0.04 user:0.00 sys:0.00 swapped:0 exitval:0 max:2412k

*** Result
FAILED_RESULT: signal detected (algo:pair numproc:229 msgsize:6650394 hostTime:0.04 hostMem:2412k)
** Test with algorithm pair_rma
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 229 ./alltoall 6650394 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:pair_rma
*** raw stdout

*** raw stderr

*** raw timing information
Command terminated by signal 2
clock:0.04 user:0.00 sys:0.00 swapped:0 exitval:0 max:2432k

*** Result
FAILED_RESULT: signal detected (algo:pair_rma numproc:229 msgsize:6650394 hostTime:0.04 hostMem:2432k)
** Test with algorithm pair_light_barrier
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 229 ./alltoall 6650394 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:pair_light_barrier
*** raw stdout

*** raw stderr

*** raw timing information
Command terminated by signal 2
clock:0.04 user:0.00 sys:0.00 swapped:0 exitval:0 max:2412k

*** Result
FAILED_RESULT: signal detected (algo:pair_light_barrier numproc:229 msgsize:6650394 hostTime:0.04 hostMem:2412k)
** Test with algorithm pair_mpi_barrier
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 229 ./alltoall 6650394 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:pair_mpi_barrier
*** raw stdout

*** raw stderr

*** raw timing information
Command terminated by signal 2
clock:0.04 user:0.00 sys:0.00 swapped:0 exitval:0 max:2376k

*** Result
FAILED_RESULT: signal detected (algo:pair_mpi_barrier numproc:229 msgsize:6650394 hostTime:0.04 hostMem:2376k)
** Test with algorithm pair_one_barrier
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 229 ./alltoall 6650394 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:pair_one_barrier
*** raw stdout

*** raw stderr

*** raw timing information
Command terminated by signal 2
clock:0.04 user:0.00 sys:0.00 swapped:0 exitval:0 max:2436k

*** Result
FAILED_RESULT: signal detected (algo:pair_one_barrier numproc:229 msgsize:6650394 hostTime:0.04 hostMem:2436k)
** Test with algorithm rdb
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 229 ./alltoall 6650394 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:rdb
*** raw stdout

*** raw stderr

*** raw timing information
Command terminated by signal 2
clock:0.04 user:0.00 sys:0.00 swapped:0 exitval:0 max:2372k

*** Result
FAILED_RESULT: signal detected (algo:rdb numproc:229 msgsize:6650394 hostTime:0.04 hostMem:2372k)
** Test with algorithm ring
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 229 ./alltoall 6650394 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:ring
*** raw stdout

*** raw stderr

*** raw timing information
Command terminated by signal 2
clock:0.04 user:0.00 sys:0.00 swapped:0 exitval:0 max:2472k

*** Result
FAILED_RESULT: signal detected (algo:ring numproc:229 msgsize:6650394 hostTime:0.04 hostMem:2472k)
** Test with algorithm ring_light_barrier
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 229 ./alltoall 6650394 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:ring_light_barrier
*** raw stdout

*** raw stderr
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/TCP_gamma' to '4194304'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/running_power' to '20000'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/alltoall' to 'ring_light_barrier'
  [0.000000] [smpi_coll/INFO] Switch to algorithm ring_light_barrier for collective alltoall
  [0.000000] [smpi_coll/INFO] Switch to algorithm ring_light_barrier for collective alltoall
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/bw_factor' to '0:0.400976530736138;1420:0.913555534273577;32768:1.07831886657594;65536:0.956083935262915;327680:0.929867998857892'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/TCP_gamma' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'maxmin/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/or' to '0:8.14025462333494e-06:8.3958813204998e-10;1420:1.26995184134793e-05:9.09218191293861e-10;32768:3.09570602567453e-05:6.95645307772806e-10;65536:0:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/os' to '0:8.9300920419081e-06:7.65438202550106e-10;1420:1.39684254077781e-05:2.97409403415968e-10;32768:1.54082820250394e-05:2.44104034252286e-10;65536:0.000237866424242424:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/sender_gap' to '0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/send_is_detached_thres' to '327680'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'workstation/model' to 'compound'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/model' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/async_small_thres' to '65536'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/lat_factor' to '0:1.35489260823384;1420:3.43725032107889;32768:5.72164710873587;65536:11.9885319715471;327680:9.65041953605594'
  [0.000000] /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:131: [simix_deployment/ERROR] Unrecoverable error at tmpnFFZc4:8. The full exception stack follows, in case it helps you to diagnose the problem.
  ** SimGrid: UNCAUGHT EXCEPTION received on ./alltoall(0): category: invalid argument; value: 0
  ** Host 'node-0.acme.org' unknown
  ** Thrown by () in this process
  [0.000000] /home/mquinson/Code/simgrid/src/xbt/ex.c:146: [xbt_ex/CRITICAL] Host 'node-0.acme.org' unknown
  
  **   In parse_process() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:28
  **   In sg_platf_new_process() at /home/mquinson/Code/simgrid/src/surf/sg_platf.c:264 (discriminator 3)
  **   In ETag_surfxml_process() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:960
  **   In surf_parse_lex() at /home/mquinson/Code/simgrid/src/surf/simgrid_dtd.c:9228
  **   In _surf_parse() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:1066
  **   In SIMIX_launch_application() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:125
  **   In smpi_main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:661
  **   In main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:520
  Aborted

*** raw timing information
Command exited with non-zero status 134
clock:0.36 user:0.05 sys:0.05 swapped:0 exitval:134 max:18920k

*** Result
FAILED_RESULT: non-zero status (algo:ring_light_barrier numproc:229 msgsize:6650394 hostTime:0.36 hostMem:18920k)
** Test with algorithm ring_mpi_barrier
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 229 ./alltoall 6650394 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:ring_mpi_barrier
*** raw stdout

*** raw stderr
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/TCP_gamma' to '4194304'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/running_power' to '20000'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/alltoall' to 'ring_mpi_barrier'
  [0.000000] [smpi_coll/INFO] Switch to algorithm ring_mpi_barrier for collective alltoall
  [0.000000] [smpi_coll/INFO] Switch to algorithm ring_mpi_barrier for collective alltoall
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/bw_factor' to '0:0.400976530736138;1420:0.913555534273577;32768:1.07831886657594;65536:0.956083935262915;327680:0.929867998857892'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/TCP_gamma' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'maxmin/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/or' to '0:8.14025462333494e-06:8.3958813204998e-10;1420:1.26995184134793e-05:9.09218191293861e-10;32768:3.09570602567453e-05:6.95645307772806e-10;65536:0:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/os' to '0:8.9300920419081e-06:7.65438202550106e-10;1420:1.39684254077781e-05:2.97409403415968e-10;32768:1.54082820250394e-05:2.44104034252286e-10;65536:0.000237866424242424:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/sender_gap' to '0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/send_is_detached_thres' to '327680'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'workstation/model' to 'compound'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/model' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/async_small_thres' to '65536'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/lat_factor' to '0:1.35489260823384;1420:3.43725032107889;32768:5.72164710873587;65536:11.9885319715471;327680:9.65041953605594'
  [0.000000] /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:131: [simix_deployment/ERROR] Unrecoverable error at tmpPmn30e:8. The full exception stack follows, in case it helps you to diagnose the problem.
  ** SimGrid: UNCAUGHT EXCEPTION received on ./alltoall(0): category: invalid argument; value: 0
  ** Host 'node-0.acme.org' unknown
  ** Thrown by () in this process
  [0.000000] /home/mquinson/Code/simgrid/src/xbt/ex.c:146: [xbt_ex/CRITICAL] Host 'node-0.acme.org' unknown
  
  **   In parse_process() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:28
  **   In sg_platf_new_process() at /home/mquinson/Code/simgrid/src/surf/sg_platf.c:264 (discriminator 3)
  **   In ETag_surfxml_process() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:960
  **   In surf_parse_lex() at /home/mquinson/Code/simgrid/src/surf/simgrid_dtd.c:9228
  **   In _surf_parse() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:1066
  **   In SIMIX_launch_application() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:125
  **   In smpi_main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:661
  **   In main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:520
  Aborted

*** raw timing information
Command exited with non-zero status 134
clock:0.39 user:0.07 sys:0.08 swapped:0 exitval:134 max:19004k

*** Result
FAILED_RESULT: non-zero status (algo:ring_mpi_barrier numproc:229 msgsize:6650394 hostTime:0.39 hostMem:19004k)
** Test with algorithm ring_one_barrier
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 229 ./alltoall 6650394 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:ring_one_barrier
*** raw stdout

*** raw stderr
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/TCP_gamma' to '4194304'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/running_power' to '20000'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/alltoall' to 'ring_one_barrier'
  [0.000000] [smpi_coll/INFO] Switch to algorithm ring_one_barrier for collective alltoall
  [0.000000] [smpi_coll/INFO] Switch to algorithm ring_one_barrier for collective alltoall
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/bw_factor' to '0:0.400976530736138;1420:0.913555534273577;32768:1.07831886657594;65536:0.956083935262915;327680:0.929867998857892'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/TCP_gamma' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'maxmin/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/or' to '0:8.14025462333494e-06:8.3958813204998e-10;1420:1.26995184134793e-05:9.09218191293861e-10;32768:3.09570602567453e-05:6.95645307772806e-10;65536:0:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/os' to '0:8.9300920419081e-06:7.65438202550106e-10;1420:1.39684254077781e-05:2.97409403415968e-10;32768:1.54082820250394e-05:2.44104034252286e-10;65536:0.000237866424242424:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/sender_gap' to '0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/send_is_detached_thres' to '327680'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'workstation/model' to 'compound'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/model' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/async_small_thres' to '65536'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/lat_factor' to '0:1.35489260823384;1420:3.43725032107889;32768:5.72164710873587;65536:11.9885319715471;327680:9.65041953605594'
  [0.000000] /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:131: [simix_deployment/ERROR] Unrecoverable error at tmprGj5QY:8. The full exception stack follows, in case it helps you to diagnose the problem.
  ** SimGrid: UNCAUGHT EXCEPTION received on ./alltoall(0): category: invalid argument; value: 0
  ** Host 'node-0.acme.org' unknown
  ** Thrown by () in this process
  [0.000000] /home/mquinson/Code/simgrid/src/xbt/ex.c:146: [xbt_ex/CRITICAL] Host 'node-0.acme.org' unknown
  
  **   In parse_process() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:28
  **   In sg_platf_new_process() at /home/mquinson/Code/simgrid/src/surf/sg_platf.c:264 (discriminator 3)
  **   In ETag_surfxml_process() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:960
  **   In surf_parse_lex() at /home/mquinson/Code/simgrid/src/surf/simgrid_dtd.c:9228
  **   In _surf_parse() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:1066
  **   In SIMIX_launch_application() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:125
  **   In smpi_main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:661
  **   In main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:520
  Aborted

*** raw timing information
Command exited with non-zero status 134
clock:0.38 user:0.06 sys:0.06 swapped:0 exitval:134 max:18908k

*** Result
FAILED_RESULT: non-zero status (algo:ring_one_barrier numproc:229 msgsize:6650394 hostTime:0.38 hostMem:18908k)
** Test with algorithm mvapich2_scatter_dest
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 229 ./alltoall 6650394 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:mvapich2_scatter_dest
*** raw stdout

*** raw stderr
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/TCP_gamma' to '4194304'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/running_power' to '20000'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/alltoall' to 'mvapich2_scatter_dest'
  [0.000000] [smpi_coll/INFO] Switch to algorithm mvapich2_scatter_dest for collective alltoall
  [0.000000] [smpi_coll/INFO] Switch to algorithm mvapich2_scatter_dest for collective alltoall
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/bw_factor' to '0:0.400976530736138;1420:0.913555534273577;32768:1.07831886657594;65536:0.956083935262915;327680:0.929867998857892'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/TCP_gamma' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'maxmin/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/or' to '0:8.14025462333494e-06:8.3958813204998e-10;1420:1.26995184134793e-05:9.09218191293861e-10;32768:3.09570602567453e-05:6.95645307772806e-10;65536:0:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/os' to '0:8.9300920419081e-06:7.65438202550106e-10;1420:1.39684254077781e-05:2.97409403415968e-10;32768:1.54082820250394e-05:2.44104034252286e-10;65536:0.000237866424242424:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/sender_gap' to '0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/send_is_detached_thres' to '327680'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'workstation/model' to 'compound'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/model' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/async_small_thres' to '65536'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/lat_factor' to '0:1.35489260823384;1420:3.43725032107889;32768:5.72164710873587;65536:11.9885319715471;327680:9.65041953605594'
  [0.000000] /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:131: [simix_deployment/ERROR] Unrecoverable error at tmpl3NP5R:8. The full exception stack follows, in case it helps you to diagnose the problem.
  ** SimGrid: UNCAUGHT EXCEPTION received on ./alltoall(0): category: invalid argument; value: 0
  ** Host 'node-0.acme.org' unknown
  ** Thrown by () in this process
  [0.000000] /home/mquinson/Code/simgrid/src/xbt/ex.c:146: [xbt_ex/CRITICAL] Host 'node-0.acme.org' unknown
  
  **   In parse_process() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:28
  **   In sg_platf_new_process() at /home/mquinson/Code/simgrid/src/surf/sg_platf.c:264 (discriminator 3)
  **   In ETag_surfxml_process() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:960
  **   In surf_parse_lex() at /home/mquinson/Code/simgrid/src/surf/simgrid_dtd.c:9228
  **   In _surf_parse() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:1066
  **   In SIMIX_launch_application() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:125
  **   In smpi_main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:661
  **   In main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:520
  Aborted

*** raw timing information
Command exited with non-zero status 134
clock:0.40 user:0.06 sys:0.06 swapped:0 exitval:134 max:19008k

*** Result
FAILED_RESULT: non-zero status (algo:mvapich2_scatter_dest numproc:229 msgsize:6650394 hostTime:0.40 hostMem:19008k)
** Test with algorithm mvapich2
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 229 ./alltoall 6650394 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:mvapich2
*** raw stdout

*** raw stderr
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/TCP_gamma' to '4194304'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/running_power' to '20000'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/alltoall' to 'mvapich2'
  [0.000000] [smpi_coll/INFO] Switch to algorithm mvapich2 for collective alltoall
  [0.000000] [smpi_coll/INFO] Switch to algorithm mvapich2 for collective alltoall
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/bw_factor' to '0:0.400976530736138;1420:0.913555534273577;32768:1.07831886657594;65536:0.956083935262915;327680:0.929867998857892'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/TCP_gamma' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'maxmin/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/or' to '0:8.14025462333494e-06:8.3958813204998e-10;1420:1.26995184134793e-05:9.09218191293861e-10;32768:3.09570602567453e-05:6.95645307772806e-10;65536:0:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/os' to '0:8.9300920419081e-06:7.65438202550106e-10;1420:1.39684254077781e-05:2.97409403415968e-10;32768:1.54082820250394e-05:2.44104034252286e-10;65536:0.000237866424242424:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/sender_gap' to '0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/send_is_detached_thres' to '327680'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'workstation/model' to 'compound'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/model' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/async_small_thres' to '65536'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/lat_factor' to '0:1.35489260823384;1420:3.43725032107889;32768:5.72164710873587;65536:11.9885319715471;327680:9.65041953605594'
  [0.000000] /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:131: [simix_deployment/ERROR] Unrecoverable error at tmpmaNSds:8. The full exception stack follows, in case it helps you to diagnose the problem.
  ** SimGrid: UNCAUGHT EXCEPTION received on ./alltoall(0): category: invalid argument; value: 0
  ** Host 'node-0.acme.org' unknown
  ** Thrown by () in this process
  [0.000000] /home/mquinson/Code/simgrid/src/xbt/ex.c:146: [xbt_ex/CRITICAL] Host 'node-0.acme.org' unknown
  
  **   In parse_process() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:28
  **   In sg_platf_new_process() at /home/mquinson/Code/simgrid/src/surf/sg_platf.c:264 (discriminator 3)
  **   In ETag_surfxml_process() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:960
  **   In surf_parse_lex() at /home/mquinson/Code/simgrid/src/surf/simgrid_dtd.c:9228
  **   In _surf_parse() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:1066
  **   In SIMIX_launch_application() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:125
  **   In smpi_main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:661
  **   In main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:520
  Aborted

*** raw timing information
Command exited with non-zero status 134
clock:0.38 user:0.06 sys:0.06 swapped:0 exitval:134 max:18932k

*** Result
FAILED_RESULT: non-zero status (algo:mvapich2 numproc:229 msgsize:6650394 hostTime:0.38 hostMem:18932k)
** Test with algorithm ompi
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 229 ./alltoall 6650394 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:ompi
*** raw stdout

*** raw stderr
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/TCP_gamma' to '4194304'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/running_power' to '20000'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/alltoall' to 'ompi'
  [0.000000] [smpi_coll/INFO] Switch to algorithm ompi for collective alltoall
  [0.000000] [smpi_coll/INFO] Switch to algorithm ompi for collective alltoall
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/bw_factor' to '0:0.400976530736138;1420:0.913555534273577;32768:1.07831886657594;65536:0.956083935262915;327680:0.929867998857892'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/TCP_gamma' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'maxmin/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/or' to '0:8.14025462333494e-06:8.3958813204998e-10;1420:1.26995184134793e-05:9.09218191293861e-10;32768:3.09570602567453e-05:6.95645307772806e-10;65536:0:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/os' to '0:8.9300920419081e-06:7.65438202550106e-10;1420:1.39684254077781e-05:2.97409403415968e-10;32768:1.54082820250394e-05:2.44104034252286e-10;65536:0.000237866424242424:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/sender_gap' to '0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/send_is_detached_thres' to '327680'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'workstation/model' to 'compound'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/model' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/async_small_thres' to '65536'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/lat_factor' to '0:1.35489260823384;1420:3.43725032107889;32768:5.72164710873587;65536:11.9885319715471;327680:9.65041953605594'
  [0.000000] /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:131: [simix_deployment/ERROR] Unrecoverable error at tmptiIriG:8. The full exception stack follows, in case it helps you to diagnose the problem.
  ** SimGrid: UNCAUGHT EXCEPTION received on ./alltoall(0): category: invalid argument; value: 0
  ** Host 'node-0.acme.org' unknown
  ** Thrown by () in this process
  [0.000000] /home/mquinson/Code/simgrid/src/xbt/ex.c:146: [xbt_ex/CRITICAL] Host 'node-0.acme.org' unknown
  
  **   In parse_process() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:28
  **   In sg_platf_new_process() at /home/mquinson/Code/simgrid/src/surf/sg_platf.c:264 (discriminator 3)
  **   In ETag_surfxml_process() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:960
  **   In surf_parse_lex() at /home/mquinson/Code/simgrid/src/surf/simgrid_dtd.c:9228
  **   In _surf_parse() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:1066
  **   In SIMIX_launch_application() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:125
  **   In smpi_main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:661
  **   In main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:520
  Aborted

*** raw timing information
Command exited with non-zero status 134
clock:0.41 user:0.07 sys:0.05 swapped:0 exitval:134 max:19012k

*** Result
FAILED_RESULT: non-zero status (algo:ompi numproc:229 msgsize:6650394 hostTime:0.41 hostMem:19012k)
** Test with algorithm mpich
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 229 ./alltoall 6650394 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:mpich
*** raw stdout

*** raw stderr
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/TCP_gamma' to '4194304'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/running_power' to '20000'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/alltoall' to 'mpich'
  [0.000000] [smpi_coll/INFO] Switch to algorithm mpich for collective alltoall
  [0.000000] [smpi_coll/INFO] Switch to algorithm mpich for collective alltoall
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/bw_factor' to '0:0.400976530736138;1420:0.913555534273577;32768:1.07831886657594;65536:0.956083935262915;327680:0.929867998857892'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/TCP_gamma' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'maxmin/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/or' to '0:8.14025462333494e-06:8.3958813204998e-10;1420:1.26995184134793e-05:9.09218191293861e-10;32768:3.09570602567453e-05:6.95645307772806e-10;65536:0:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/os' to '0:8.9300920419081e-06:7.65438202550106e-10;1420:1.39684254077781e-05:2.97409403415968e-10;32768:1.54082820250394e-05:2.44104034252286e-10;65536:0.000237866424242424:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/sender_gap' to '0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/send_is_detached_thres' to '327680'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'workstation/model' to 'compound'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/model' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/async_small_thres' to '65536'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/lat_factor' to '0:1.35489260823384;1420:3.43725032107889;32768:5.72164710873587;65536:11.9885319715471;327680:9.65041953605594'
  [0.000000] /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:131: [simix_deployment/ERROR] Unrecoverable error at tmp8c3JsM:8. The full exception stack follows, in case it helps you to diagnose the problem.
  ** SimGrid: UNCAUGHT EXCEPTION received on ./alltoall(0): category: invalid argument; value: 0
  ** Host 'node-0.acme.org' unknown
  ** Thrown by () in this process
  [0.000000] /home/mquinson/Code/simgrid/src/xbt/ex.c:146: [xbt_ex/CRITICAL] Host 'node-0.acme.org' unknown
  
  **   In parse_process() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:28
  **   In sg_platf_new_process() at /home/mquinson/Code/simgrid/src/surf/sg_platf.c:264 (discriminator 3)
  **   In ETag_surfxml_process() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:960
  **   In surf_parse_lex() at /home/mquinson/Code/simgrid/src/surf/simgrid_dtd.c:9228
  **   In _surf_parse() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:1066
  **   In SIMIX_launch_application() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:125
  **   In smpi_main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:661
  **   In main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:520
  Aborted

*** raw timing information
Command exited with non-zero status 134
clock:0.40 user:0.06 sys:0.08 swapped:0 exitval:134 max:18924k

*** Result
FAILED_RESULT: non-zero status (algo:mpich numproc:229 msgsize:6650394 hostTime:0.40 hostMem:18924k)
** Test with algorithm impi
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 229 ./alltoall 6650394 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:impi
*** raw stdout

*** raw stderr
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/TCP_gamma' to '4194304'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/running_power' to '20000'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/alltoall' to 'impi'
  [0.000000] [smpi_coll/INFO] Switch to algorithm impi for collective alltoall
  [0.000000] [smpi_coll/INFO] Switch to algorithm impi for collective alltoall
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/bw_factor' to '0:0.400976530736138;1420:0.913555534273577;32768:1.07831886657594;65536:0.956083935262915;327680:0.929867998857892'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/TCP_gamma' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'maxmin/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/or' to '0:8.14025462333494e-06:8.3958813204998e-10;1420:1.26995184134793e-05:9.09218191293861e-10;32768:3.09570602567453e-05:6.95645307772806e-10;65536:0:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/os' to '0:8.9300920419081e-06:7.65438202550106e-10;1420:1.39684254077781e-05:2.97409403415968e-10;32768:1.54082820250394e-05:2.44104034252286e-10;65536:0.000237866424242424:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/sender_gap' to '0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/send_is_detached_thres' to '327680'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'workstation/model' to 'compound'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/model' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/async_small_thres' to '65536'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/lat_factor' to '0:1.35489260823384;1420:3.43725032107889;32768:5.72164710873587;65536:11.9885319715471;327680:9.65041953605594'
  [0.000000] /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:131: [simix_deployment/ERROR] Unrecoverable error at tmpBrkAVj:8. The full exception stack follows, in case it helps you to diagnose the problem.
  ** SimGrid: UNCAUGHT EXCEPTION received on ./alltoall(0): category: invalid argument; value: 0
  ** Host 'node-0.acme.org' unknown
  ** Thrown by () in this process
  [0.000000] /home/mquinson/Code/simgrid/src/xbt/ex.c:146: [xbt_ex/CRITICAL] Host 'node-0.acme.org' unknown
  
  **   In parse_process() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:28
  **   In sg_platf_new_process() at /home/mquinson/Code/simgrid/src/surf/sg_platf.c:264 (discriminator 3)
  **   In ETag_surfxml_process() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:960
  **   In surf_parse_lex() at /home/mquinson/Code/simgrid/src/surf/simgrid_dtd.c:9228
  **   In _surf_parse() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:1066
  **   In SIMIX_launch_application() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:125
  **   In smpi_main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:661
  **   In main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:520
  Aborted

*** raw timing information
Command exited with non-zero status 134
clock:0.40 user:0.05 sys:0.07 swapped:0 exitval:134 max:18772k

*** Result
FAILED_RESULT: non-zero status (algo:impi numproc:229 msgsize:6650394 hostTime:0.40 hostMem:18772k)
* Experiment 3
Do proc:661 size:545427 freemem:10927032k mem usage:721054494
** Test with algorithm 2dmesh
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 661 ./alltoall 545427 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:2dmesh
*** raw stdout

*** raw stderr
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/TCP_gamma' to '4194304'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/running_power' to '20000'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/alltoall' to '2dmesh'
  [0.000000] [smpi_coll/INFO] Switch to algorithm 2dmesh for collective alltoall
  [0.000000] [smpi_coll/INFO] Switch to algorithm 2dmesh for collective alltoall
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/bw_factor' to '0:0.400976530736138;1420:0.913555534273577;32768:1.07831886657594;65536:0.956083935262915;327680:0.929867998857892'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/TCP_gamma' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'maxmin/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/or' to '0:8.14025462333494e-06:8.3958813204998e-10;1420:1.26995184134793e-05:9.09218191293861e-10;32768:3.09570602567453e-05:6.95645307772806e-10;65536:0:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/os' to '0:8.9300920419081e-06:7.65438202550106e-10;1420:1.39684254077781e-05:2.97409403415968e-10;32768:1.54082820250394e-05:2.44104034252286e-10;65536:0.000237866424242424:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/sender_gap' to '0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/send_is_detached_thres' to '327680'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'workstation/model' to 'compound'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/model' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/async_small_thres' to '65536'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/lat_factor' to '0:1.35489260823384;1420:3.43725032107889;32768:5.72164710873587;65536:11.9885319715471;327680:9.65041953605594'
  [0.000000] /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:131: [simix_deployment/ERROR] Unrecoverable error at tmpwBFI0a:8. The full exception stack follows, in case it helps you to diagnose the problem.
  ** SimGrid: UNCAUGHT EXCEPTION received on ./alltoall(0): category: invalid argument; value: 0
  ** Host 'node-0.acme.org' unknown
  ** Thrown by () in this process
  [0.000000] /home/mquinson/Code/simgrid/src/xbt/ex.c:146: [xbt_ex/CRITICAL] Host 'node-0.acme.org' unknown
  
  **   In parse_process() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:28
  **   In sg_platf_new_process() at /home/mquinson/Code/simgrid/src/surf/sg_platf.c:264 (discriminator 3)
  **   In ETag_surfxml_process() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:960
  **   In surf_parse_lex() at /home/mquinson/Code/simgrid/src/surf/simgrid_dtd.c:9228
  **   In _surf_parse() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:1066
  **   In SIMIX_launch_application() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:125
  **   In smpi_main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:661
  **   In main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:520
  Aborted

*** raw timing information
Command exited with non-zero status 134
clock:0.88 user:0.08 sys:0.10 swapped:0 exitval:134 max:19016k

*** Result
FAILED_RESULT: non-zero status (algo:2dmesh numproc:661 msgsize:545427 hostTime:0.88 hostMem:19016k)
** Test with algorithm 3dmesh
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 661 ./alltoall 545427 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:3dmesh
*** raw stdout

*** raw stderr
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/TCP_gamma' to '4194304'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/running_power' to '20000'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/alltoall' to '3dmesh'
  [0.000000] [smpi_coll/INFO] Switch to algorithm 3dmesh for collective alltoall
  [0.000000] [smpi_coll/INFO] Switch to algorithm 3dmesh for collective alltoall
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/bw_factor' to '0:0.400976530736138;1420:0.913555534273577;32768:1.07831886657594;65536:0.956083935262915;327680:0.929867998857892'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/TCP_gamma' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'maxmin/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/or' to '0:8.14025462333494e-06:8.3958813204998e-10;1420:1.26995184134793e-05:9.09218191293861e-10;32768:3.09570602567453e-05:6.95645307772806e-10;65536:0:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/os' to '0:8.9300920419081e-06:7.65438202550106e-10;1420:1.39684254077781e-05:2.97409403415968e-10;32768:1.54082820250394e-05:2.44104034252286e-10;65536:0.000237866424242424:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/sender_gap' to '0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/send_is_detached_thres' to '327680'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'workstation/model' to 'compound'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/model' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/async_small_thres' to '65536'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/lat_factor' to '0:1.35489260823384;1420:3.43725032107889;32768:5.72164710873587;65536:11.9885319715471;327680:9.65041953605594'
  [0.000000] /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:131: [simix_deployment/ERROR] Unrecoverable error at tmp0dUIal:8. The full exception stack follows, in case it helps you to diagnose the problem.
  ** SimGrid: UNCAUGHT EXCEPTION received on ./alltoall(0): category: invalid argument; value: 0
  ** Host 'node-0.acme.org' unknown
  ** Thrown by () in this process
  [0.000000] /home/mquinson/Code/simgrid/src/xbt/ex.c:146: [xbt_ex/CRITICAL] Host 'node-0.acme.org' unknown
  
  **   In parse_process() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:28
  **   In sg_platf_new_process() at /home/mquinson/Code/simgrid/src/surf/sg_platf.c:264 (discriminator 3)
  **   In ETag_surfxml_process() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:960
  **   In surf_parse_lex() at /home/mquinson/Code/simgrid/src/surf/simgrid_dtd.c:9228
  **   In _surf_parse() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:1066
  **   In SIMIX_launch_application() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:125
  **   In smpi_main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:661
  **   In main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:520
  Aborted

*** raw timing information
Command exited with non-zero status 134
clock:0.86 user:0.08 sys:0.13 swapped:0 exitval:134 max:18956k

*** Result
FAILED_RESULT: non-zero status (algo:3dmesh numproc:661 msgsize:545427 hostTime:0.86 hostMem:18956k)
** Test with algorithm basic_linear
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 661 ./alltoall 545427 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:basic_linear
*** raw stdout

*** raw stderr
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/TCP_gamma' to '4194304'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/running_power' to '20000'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/alltoall' to 'basic_linear'
  [0.000000] [smpi_coll/INFO] Switch to algorithm basic_linear for collective alltoall
  [0.000000] [smpi_coll/INFO] Switch to algorithm basic_linear for collective alltoall
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/bw_factor' to '0:0.400976530736138;1420:0.913555534273577;32768:1.07831886657594;65536:0.956083935262915;327680:0.929867998857892'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/TCP_gamma' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'maxmin/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/or' to '0:8.14025462333494e-06:8.3958813204998e-10;1420:1.26995184134793e-05:9.09218191293861e-10;32768:3.09570602567453e-05:6.95645307772806e-10;65536:0:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/os' to '0:8.9300920419081e-06:7.65438202550106e-10;1420:1.39684254077781e-05:2.97409403415968e-10;32768:1.54082820250394e-05:2.44104034252286e-10;65536:0.000237866424242424:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/sender_gap' to '0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/send_is_detached_thres' to '327680'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'workstation/model' to 'compound'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/model' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/async_small_thres' to '65536'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/lat_factor' to '0:1.35489260823384;1420:3.43725032107889;32768:5.72164710873587;65536:11.9885319715471;327680:9.65041953605594'
  [0.000000] /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:131: [simix_deployment/ERROR] Unrecoverable error at tmpxV9DEp:8. The full exception stack follows, in case it helps you to diagnose the problem.
  ** SimGrid: UNCAUGHT EXCEPTION received on ./alltoall(0): category: invalid argument; value: 0
  ** Host 'node-0.acme.org' unknown
  ** Thrown by () in this process
  [0.000000] /home/mquinson/Code/simgrid/src/xbt/ex.c:146: [xbt_ex/CRITICAL] Host 'node-0.acme.org' unknown
  
  **   In parse_process() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:28
  **   In sg_platf_new_process() at /home/mquinson/Code/simgrid/src/surf/sg_platf.c:264 (discriminator 3)
  **   In ETag_surfxml_process() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:960
  **   In surf_parse_lex() at /home/mquinson/Code/simgrid/src/surf/simgrid_dtd.c:9228
  **   In _surf_parse() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:1066
  **   In SIMIX_launch_application() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:125
  **   In smpi_main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:661
  **   In main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:520
  Aborted

*** raw timing information
Command exited with non-zero status 134
clock:0.83 user:0.08 sys:0.09 swapped:0 exitval:134 max:18788k

*** Result
FAILED_RESULT: non-zero status (algo:basic_linear numproc:661 msgsize:545427 hostTime:0.83 hostMem:18788k)
** Test with algorithm bruck
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 661 ./alltoall 545427 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:bruck
*** raw stdout

*** raw stderr
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/TCP_gamma' to '4194304'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/running_power' to '20000'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/alltoall' to 'bruck'
  [0.000000] [smpi_coll/INFO] Switch to algorithm bruck for collective alltoall
  [0.000000] [smpi_coll/INFO] Switch to algorithm bruck for collective alltoall
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/bw_factor' to '0:0.400976530736138;1420:0.913555534273577;32768:1.07831886657594;65536:0.956083935262915;327680:0.929867998857892'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/TCP_gamma' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'maxmin/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/or' to '0:8.14025462333494e-06:8.3958813204998e-10;1420:1.26995184134793e-05:9.09218191293861e-10;32768:3.09570602567453e-05:6.95645307772806e-10;65536:0:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/os' to '0:8.9300920419081e-06:7.65438202550106e-10;1420:1.39684254077781e-05:2.97409403415968e-10;32768:1.54082820250394e-05:2.44104034252286e-10;65536:0.000237866424242424:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/sender_gap' to '0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/send_is_detached_thres' to '327680'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'workstation/model' to 'compound'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/model' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/async_small_thres' to '65536'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/lat_factor' to '0:1.35489260823384;1420:3.43725032107889;32768:5.72164710873587;65536:11.9885319715471;327680:9.65041953605594'
  [0.000000] /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:131: [simix_deployment/ERROR] Unrecoverable error at tmp6XAJQm:8. The full exception stack follows, in case it helps you to diagnose the problem.
  ** SimGrid: UNCAUGHT EXCEPTION received on ./alltoall(0): category: invalid argument; value: 0
  ** Host 'node-0.acme.org' unknown
  ** Thrown by () in this process
  [0.000000] /home/mquinson/Code/simgrid/src/xbt/ex.c:146: [xbt_ex/CRITICAL] Host 'node-0.acme.org' unknown
  
  **   In parse_process() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:28
  **   In sg_platf_new_process() at /home/mquinson/Code/simgrid/src/surf/sg_platf.c:264 (discriminator 3)
  **   In ETag_surfxml_process() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:960
  **   In surf_parse_lex() at /home/mquinson/Code/simgrid/src/surf/simgrid_dtd.c:9228
  **   In _surf_parse() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:1066
  **   In SIMIX_launch_application() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:125
  **   In smpi_main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:661
  **   In main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:520
  Aborted

*** raw timing information
Command exited with non-zero status 134
clock:0.84 user:0.07 sys:0.12 swapped:0 exitval:134 max:19004k

*** Result
FAILED_RESULT: non-zero status (algo:bruck numproc:661 msgsize:545427 hostTime:0.84 hostMem:19004k)
** Test with algorithm pair
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 661 ./alltoall 545427 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:pair
*** raw stdout

*** raw stderr
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/TCP_gamma' to '4194304'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/running_power' to '20000'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/alltoall' to 'pair'
  [0.000000] [smpi_coll/INFO] Switch to algorithm pair for collective alltoall
  [0.000000] [smpi_coll/INFO] Switch to algorithm pair for collective alltoall
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/bw_factor' to '0:0.400976530736138;1420:0.913555534273577;32768:1.07831886657594;65536:0.956083935262915;327680:0.929867998857892'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/TCP_gamma' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'maxmin/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/or' to '0:8.14025462333494e-06:8.3958813204998e-10;1420:1.26995184134793e-05:9.09218191293861e-10;32768:3.09570602567453e-05:6.95645307772806e-10;65536:0:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/os' to '0:8.9300920419081e-06:7.65438202550106e-10;1420:1.39684254077781e-05:2.97409403415968e-10;32768:1.54082820250394e-05:2.44104034252286e-10;65536:0.000237866424242424:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/sender_gap' to '0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/send_is_detached_thres' to '327680'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'workstation/model' to 'compound'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/model' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/async_small_thres' to '65536'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/lat_factor' to '0:1.35489260823384;1420:3.43725032107889;32768:5.72164710873587;65536:11.9885319715471;327680:9.65041953605594'
  [0.000000] /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:131: [simix_deployment/ERROR] Unrecoverable error at tmpife4HI:8. The full exception stack follows, in case it helps you to diagnose the problem.
  ** SimGrid: UNCAUGHT EXCEPTION received on ./alltoall(0): category: invalid argument; value: 0
  ** Host 'node-0.acme.org' unknown
  ** Thrown by () in this process
  [0.000000] /home/mquinson/Code/simgrid/src/xbt/ex.c:146: [xbt_ex/CRITICAL] Host 'node-0.acme.org' unknown
  
  **   In parse_process() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:28
  **   In sg_platf_new_process() at /home/mquinson/Code/simgrid/src/surf/sg_platf.c:264 (discriminator 3)
  **   In ETag_surfxml_process() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:960
  **   In surf_parse_lex() at /home/mquinson/Code/simgrid/src/surf/simgrid_dtd.c:9228
  **   In _surf_parse() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:1066
  **   In SIMIX_launch_application() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:125
  **   In smpi_main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:661
  **   In main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:520
  Aborted

*** raw timing information
Command exited with non-zero status 134
clock:0.87 user:0.05 sys:0.14 swapped:0 exitval:134 max:18932k

*** Result
FAILED_RESULT: non-zero status (algo:pair numproc:661 msgsize:545427 hostTime:0.87 hostMem:18932k)
** Test with algorithm pair_rma
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 661 ./alltoall 545427 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:pair_rma
*** raw stdout

*** raw stderr
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/TCP_gamma' to '4194304'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/running_power' to '20000'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/alltoall' to 'pair_rma'
  [0.000000] [smpi_coll/INFO] Switch to algorithm pair_rma for collective alltoall
  [0.000000] [smpi_coll/INFO] Switch to algorithm pair_rma for collective alltoall
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/bw_factor' to '0:0.400976530736138;1420:0.913555534273577;32768:1.07831886657594;65536:0.956083935262915;327680:0.929867998857892'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/TCP_gamma' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'maxmin/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/or' to '0:8.14025462333494e-06:8.3958813204998e-10;1420:1.26995184134793e-05:9.09218191293861e-10;32768:3.09570602567453e-05:6.95645307772806e-10;65536:0:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/os' to '0:8.9300920419081e-06:7.65438202550106e-10;1420:1.39684254077781e-05:2.97409403415968e-10;32768:1.54082820250394e-05:2.44104034252286e-10;65536:0.000237866424242424:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/sender_gap' to '0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/send_is_detached_thres' to '327680'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'workstation/model' to 'compound'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/model' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/async_small_thres' to '65536'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/lat_factor' to '0:1.35489260823384;1420:3.43725032107889;32768:5.72164710873587;65536:11.9885319715471;327680:9.65041953605594'
  [0.000000] /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:131: [simix_deployment/ERROR] Unrecoverable error at tmpwz15Ds:8. The full exception stack follows, in case it helps you to diagnose the problem.
  ** SimGrid: UNCAUGHT EXCEPTION received on ./alltoall(0): category: invalid argument; value: 0
  ** Host 'node-0.acme.org' unknown
  ** Thrown by () in this process
  [0.000000] /home/mquinson/Code/simgrid/src/xbt/ex.c:146: [xbt_ex/CRITICAL] Host 'node-0.acme.org' unknown
  
  **   In parse_process() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:28
  **   In sg_platf_new_process() at /home/mquinson/Code/simgrid/src/surf/sg_platf.c:264 (discriminator 3)
  **   In ETag_surfxml_process() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:960
  **   In surf_parse_lex() at /home/mquinson/Code/simgrid/src/surf/simgrid_dtd.c:9228
  **   In _surf_parse() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:1066
  **   In SIMIX_launch_application() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:125
  **   In smpi_main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:661
  **   In main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:520
  Aborted

*** raw timing information
Command exited with non-zero status 134
clock:0.84 user:0.05 sys:0.12 swapped:0 exitval:134 max:19008k

*** Result
FAILED_RESULT: non-zero status (algo:pair_rma numproc:661 msgsize:545427 hostTime:0.84 hostMem:19008k)
** Test with algorithm pair_light_barrier
*** Command
smpirun -platform graphene_1024.xml -hostfile hostfile -np 661 ./alltoall 545427 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:pair_light_barrier
*** raw stdout

*** raw stderr
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/TCP_gamma' to '4194304'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/running_power' to '20000'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/alltoall' to 'pair_light_barrier'
  [0.000000] [smpi_coll/INFO] Switch to algorithm pair_light_barrier for collective alltoall
  [0.000000] [smpi_coll/INFO] Switch to algorithm pair_light_barrier for collective alltoall
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/bw_factor' to '0:0.400976530736138;1420:0.913555534273577;32768:1.07831886657594;65536:0.956083935262915;327680:0.929867998857892'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/TCP_gamma' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'maxmin/precision' to '1e-9'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/or' to '0:8.14025462333494e-06:8.3958813204998e-10;1420:1.26995184134793e-05:9.09218191293861e-10;32768:3.09570602567453e-05:6.95645307772806e-10;65536:0:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/os' to '0:8.9300920419081e-06:7.65438202550106e-10;1420:1.39684254077781e-05:2.97409403415968e-10;32768:1.54082820250394e-05:2.44104034252286e-10;65536:0.000237866424242424:0;327680:0:0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/sender_gap' to '0'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/send_is_detached_thres' to '327680'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'workstation/model' to 'compound'
  [0.000000] [surf_parse/INFO] The custom configuration 'network/model' is already defined by user!
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/async_small_thres' to '65536'
  [0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/lat_factor' to '0:1.35489260823384;1420:3.43725032107889;32768:5.72164710873587;65536:11.9885319715471;327680:9.65041953605594'
  [0.000000] /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:131: [simix_deployment/ERROR] Unrecoverable error at tmpj4Gm9I:8. The full exception stack follows, in case it helps you to diagnose the problem.
  ** SimGrid: UNCAUGHT EXCEPTION received on ./alltoall(0): category: invalid argument; value: 0
  ** Host 'node-0.acme.org' unknown
  ** Thrown by () in this process
  [0.000000] /home/mquinson/Code/simgrid/src/xbt/ex.c:146: [xbt_ex/CRITICAL] Host 'node-0.acme.org' unknown
  
  **   In parse_process() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:28
  **   In sg_platf_new_process() at /home/mquinson/Code/simgrid/src/surf/sg_platf.c:264 (discriminator 3)
  **   In ETag_surfxml_process() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:960
  **   In surf_parse_lex() at /home/mquinson/Code/simgrid/src/surf/simgrid_dtd.c:9228
  **   In _surf_parse() at /home/mquinson/Code/simgrid/src/surf/surfxml_parse.c:1066
  **   In SIMIX_launch_application() at /home/mquinson/Code/simgrid/src/simix/smx_deployment.c:125
  **   In smpi_main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:661
  **   In main() at /home/mquinson/Code/simgrid/src/smpi/smpi_global.c:520
  Aborted

*** raw timing information
Command exited with non-zero status 134
clock:0.84 user:0.06 sys:0.11 swapped:0 exitval:134 max:19016k

*** Result
FAILED_RESULT: non-zero status (algo:pair_light_barrier numproc:661 msgsize:545427 hostTime:0.84 hostMem:19016k)
** Test with algorithm pair_mpi_barrier
