#+TITLE: SMPI Collective evaluation
#+DATE: Tue Feb 24 20:34:41 CET 2015
#+AUTHOR: mquinson
 
* People logged when experiment started:
* Hostname
graphite-4.nancy.grid5000.fr
* System information
Linux graphite-4.nancy.grid5000.fr 3.2.0-4-amd64 #1 SMP Debian 3.2.63-2+deb7u1 x86_64 GNU/Linux
* CPU info
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 45
model name	: Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
stepping	: 7
microcode	: 0x710
cpu MHz		: 2000.137
cache size	: 20480 KB
physical id	: 0
siblings	: 8
core id		: 0
cpu cores	: 8
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm arat xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid
bogomips	: 4000.27
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 45
model name	: Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
stepping	: 7
microcode	: 0x710
cpu MHz		: 2000.137
cache size	: 20480 KB
physical id	: 1
siblings	: 8
core id		: 0
cpu cores	: 8
apicid		: 32
initial apicid	: 32
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm arat xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid
bogomips	: 3999.96
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 2
vendor_id	: GenuineIntel
cpu family	: 6
model		: 45
model name	: Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
stepping	: 7
microcode	: 0x710
cpu MHz		: 2000.137
cache size	: 20480 KB
physical id	: 0
siblings	: 8
core id		: 1
cpu cores	: 8
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm arat xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid
bogomips	: 3999.96
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 45
model name	: Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
stepping	: 7
microcode	: 0x710
cpu MHz		: 2000.137
cache size	: 20480 KB
physical id	: 1
siblings	: 8
core id		: 1
cpu cores	: 8
apicid		: 34
initial apicid	: 34
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm arat xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid
bogomips	: 3999.94
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 4
vendor_id	: GenuineIntel
cpu family	: 6
model		: 45
model name	: Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
stepping	: 7
microcode	: 0x710
cpu MHz		: 2000.137
cache size	: 20480 KB
physical id	: 0
siblings	: 8
core id		: 2
cpu cores	: 8
apicid		: 4
initial apicid	: 4
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm arat xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid
bogomips	: 3999.96
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 5
vendor_id	: GenuineIntel
cpu family	: 6
model		: 45
model name	: Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
stepping	: 7
microcode	: 0x710
cpu MHz		: 2000.137
cache size	: 20480 KB
physical id	: 1
siblings	: 8
core id		: 2
cpu cores	: 8
apicid		: 36
initial apicid	: 36
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm arat xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid
bogomips	: 3999.88
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 6
vendor_id	: GenuineIntel
cpu family	: 6
model		: 45
model name	: Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
stepping	: 7
microcode	: 0x710
cpu MHz		: 2000.137
cache size	: 20480 KB
physical id	: 0
siblings	: 8
core id		: 3
cpu cores	: 8
apicid		: 6
initial apicid	: 6
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm arat xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid
bogomips	: 3999.96
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 7
vendor_id	: GenuineIntel
cpu family	: 6
model		: 45
model name	: Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
stepping	: 7
microcode	: 0x710
cpu MHz		: 2000.137
cache size	: 20480 KB
physical id	: 1
siblings	: 8
core id		: 3
cpu cores	: 8
apicid		: 38
initial apicid	: 38
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm arat xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid
bogomips	: 3999.93
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 8
vendor_id	: GenuineIntel
cpu family	: 6
model		: 45
model name	: Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
stepping	: 7
microcode	: 0x710
cpu MHz		: 2000.137
cache size	: 20480 KB
physical id	: 0
siblings	: 8
core id		: 4
cpu cores	: 8
apicid		: 8
initial apicid	: 8
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm arat xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid
bogomips	: 3999.95
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 9
vendor_id	: GenuineIntel
cpu family	: 6
model		: 45
model name	: Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
stepping	: 7
microcode	: 0x710
cpu MHz		: 2000.137
cache size	: 20480 KB
physical id	: 1
siblings	: 8
core id		: 4
cpu cores	: 8
apicid		: 40
initial apicid	: 40
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm arat xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid
bogomips	: 3999.97
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 10
vendor_id	: GenuineIntel
cpu family	: 6
model		: 45
model name	: Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
stepping	: 7
microcode	: 0x710
cpu MHz		: 2000.137
cache size	: 20480 KB
physical id	: 0
siblings	: 8
core id		: 5
cpu cores	: 8
apicid		: 10
initial apicid	: 10
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm arat xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid
bogomips	: 3999.97
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 11
vendor_id	: GenuineIntel
cpu family	: 6
model		: 45
model name	: Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
stepping	: 7
microcode	: 0x710
cpu MHz		: 2000.137
cache size	: 20480 KB
physical id	: 1
siblings	: 8
core id		: 5
cpu cores	: 8
apicid		: 42
initial apicid	: 42
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm arat xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid
bogomips	: 3999.87
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 12
vendor_id	: GenuineIntel
cpu family	: 6
model		: 45
model name	: Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
stepping	: 7
microcode	: 0x710
cpu MHz		: 2000.137
cache size	: 20480 KB
physical id	: 0
siblings	: 8
core id		: 6
cpu cores	: 8
apicid		: 12
initial apicid	: 12
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm arat xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid
bogomips	: 3999.97
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 13
vendor_id	: GenuineIntel
cpu family	: 6
model		: 45
model name	: Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
stepping	: 7
microcode	: 0x710
cpu MHz		: 2000.137
cache size	: 20480 KB
physical id	: 1
siblings	: 8
core id		: 6
cpu cores	: 8
apicid		: 44
initial apicid	: 44
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm arat xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid
bogomips	: 3999.97
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 14
vendor_id	: GenuineIntel
cpu family	: 6
model		: 45
model name	: Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
stepping	: 7
microcode	: 0x710
cpu MHz		: 2000.137
cache size	: 20480 KB
physical id	: 0
siblings	: 8
core id		: 7
cpu cores	: 8
apicid		: 14
initial apicid	: 14
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm arat xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid
bogomips	: 3999.95
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 15
vendor_id	: GenuineIntel
cpu family	: 6
model		: 45
model name	: Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
stepping	: 7
microcode	: 0x710
cpu MHz		: 2000.137
cache size	: 20480 KB
physical id	: 1
siblings	: 8
core id		: 7
cpu cores	: 8
apicid		: 46
initial apicid	: 46
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm arat xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid
bogomips	: 3999.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

* CPU governor
Unknown (information not available)
* CPU frequency
Unknown (information not available)
* Meminfo
MemTotal:       264640556 kB
MemFree:        263788120 kB
Buffers:           25332 kB
Cached:           241808 kB
SwapCached:            0 kB
Active:           109024 kB
Inactive:         180400 kB
Active(anon):      24684 kB
Inactive(anon):      688 kB
Active(file):      84340 kB
Inactive(file):   179712 kB
Unevictable:        3504 kB
Mlocked:            3504 kB
SwapTotal:       3905532 kB
SwapFree:        3905532 kB
Dirty:                16 kB
Writeback:             0 kB
AnonPages:         25912 kB
Mapped:            15912 kB
Shmem:               872 kB
Slab:              81760 kB
SReclaimable:      13324 kB
SUnreclaim:        68436 kB
KernelStack:        2384 kB
PageTables:         2912 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    136225808 kB
Committed_AS:     284024 kB
VmallocTotal:   34359738367 kB
VmallocUsed:    17463336 kB
VmallocChunk:   34208066616 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:       89024 kB
DirectMap2M:     5107712 kB
DirectMap1G:    263192576 kB
* Memory hierarchy
Machine (256GB)
  NUMANode L#0 (P#0 128GB)
    Socket L#0 + L3 L#0 (20MB)
      L2 L#0 (256KB) + L1 L#0 (32KB) + Core L#0 + PU L#0 (P#0)
      L2 L#1 (256KB) + L1 L#1 (32KB) + Core L#1 + PU L#1 (P#2)
      L2 L#2 (256KB) + L1 L#2 (32KB) + Core L#2 + PU L#2 (P#4)
      L2 L#3 (256KB) + L1 L#3 (32KB) + Core L#3 + PU L#3 (P#6)
      L2 L#4 (256KB) + L1 L#4 (32KB) + Core L#4 + PU L#4 (P#8)
      L2 L#5 (256KB) + L1 L#5 (32KB) + Core L#5 + PU L#5 (P#10)
      L2 L#6 (256KB) + L1 L#6 (32KB) + Core L#6 + PU L#6 (P#12)
      L2 L#7 (256KB) + L1 L#7 (32KB) + Core L#7 + PU L#7 (P#14)
    HostBridge L#0
      PCIBridge
        PCI 8086:10fb
          Net L#0 "eth0"
        PCI 8086:10fb
          Net L#1 "eth1"
      PCIBridge
        PCI 1000:0073
          Block L#2 "sda"
          Block L#3 "sdb"
      PCIBridge
        PCI 8086:1521
          Net L#4 "eth2"
        PCI 8086:1521
          Net L#5 "eth3"
      PCIBridge
        PCIBridge
          PCIBridge
            PCIBridge
              PCI 102b:0534
      PCI 8086:1d02
        Block L#6 "sr0"
  NUMANode L#1 (P#1 128GB)
    Socket L#1 + L3 L#1 (20MB)
      L2 L#8 (256KB) + L1 L#8 (32KB) + Core L#8 + PU L#8 (P#1)
      L2 L#9 (256KB) + L1 L#9 (32KB) + Core L#9 + PU L#9 (P#3)
      L2 L#10 (256KB) + L1 L#10 (32KB) + Core L#10 + PU L#10 (P#5)
      L2 L#11 (256KB) + L1 L#11 (32KB) + Core L#11 + PU L#11 (P#7)
      L2 L#12 (256KB) + L1 L#12 (32KB) + Core L#12 + PU L#12 (P#9)
      L2 L#13 (256KB) + L1 L#13 (32KB) + Core L#13 + PU L#13 (P#11)
      L2 L#14 (256KB) + L1 L#14 (32KB) + Core L#14 + PU L#14 (P#13)
      L2 L#15 (256KB) + L1 L#15 (32KB) + Core L#15 + PU L#15 (P#15)
    HostBridge L#8
      PCIBridge
        PCI 8086:225c
* Environment Variables
OAR_JOBID=605817
OAR_ARRAYID=605817
OARDIR=/usr/lib/oar
OAR_WORKING_DIRECTORY=/home/mquinson
TERM=unknown
SHELL=/bin/bash
XDG_SESSION_COOKIE=889921aa795bbff72da6de65547ece7b-1424806481.208069-905212356
PERL5LIB=/usr/lib/oar
OARCONFFILE=/etc/oar/oar.conf
OAR_USER=mquinson
LC_ALL=en_US.UTF-8
USER=mquinson
OAR_WORKDIR=/home/mquinson
OARUSER=oar
OAR_JOB_NAME=
OAR_NODE_FILE=/var/lib/oar/605817
OAR_KEY=1
OAR_RESOURCE_PROPERTIES_FILE=/var/lib/oar/605817_resources
PATH=/home/mquinson/simgrid-3.12/bin:/usr/lib/oar/oardodo:/usr/lib/oar/oardodo:/usr/local/bin:/usr/bin:/bin:/grid5000/code/bin:/home/mquinson/bin:/home/mquinson/bin:/home/mquinson/bin
OAR_PROJECT_NAME=default
OAR_JOB_WALLTIME_SECONDS=259200
OAR_STDERR=OAR.605817.stderr
PWD=/home/mquinson/Code/SMPI-modeling/collectives
LANG=en_US.UTF-8
P4_GLOBMEMSIZE=33554432
OAR_ARRAY_ID=605817
SUDO_COMMAND=OAR
OAR_FILE_NODES=/var/lib/oar/605817
SHLVL=3
HOME=/home/mquinson
LANGUAGE=en_US:en
OAR_ARRAYINDEX=1
OARXAUTHLOCATION=/usr/bin/xauth
OAR_JOB_WALLTIME=72:0:0
BASH_ENV=/home/mquinson/.bashrc
OAR_NODEFILE=/var/lib/oar/605817
LOGNAME=mquinson
SSH_CONNECTION=172.16.79.114 58073 172.16.68.4 6667
OAR_RESOURCE_FILE=/var/lib/oar/605817
OAR_STDOUT=OAR.605817.stdout
OARDO_USER=oar
OAR_JOB_ID=605817
OAR_CPUSET=/oar/mquinson_605817
OAR_ARRAY_INDEX=1
OAR_O_WORKDIR=/home/mquinson
OARDO_UID=112
_=/usr/bin/printenv
* Tools Versions
** SimGrid Full Version
SimGrid version 3.12-devel
Copyright (c) 2004-2015. The Simgrid Team.
Release build at commit 5a97de8 (2015-02-18 10:05:16 +0100)
** SimGrid Commit Hash
5a97de8c98502af9f74cfceb924fa02e0fd80925
** Linux and gcc versions
Linux version 3.2.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.6.3 (Debian 4.6.3-14) ) #1 SMP Debian 3.2.63-2+deb7u1
** Gcc info
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.7/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 4.7.2-5' --with-bugurl=file:///usr/share/doc/gcc-4.7/README.Bugs --enable-languages=c,c++,go,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.7 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.7 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --with-arch-32=i586 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.7.2 (Debian 4.7.2-5) 
** Make tool
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for x86_64-pc-linux-gnu
** CMake
cmake version 2.8.9
* Compilation result
* Platform file
<?xml version='1.0'?>
<!DOCTYPE platform SYSTEM "http://simgrid.gforge.inria.fr/simgrid.dtd">
<platform version="3">


<config id="General">
  <prop id="workstation/model" value="compound"/>
  <prop id="network/model" value="SMPI"/>
  <prop id="network/TCP_gamma" value="4194304"/>
  <prop id="network/sender_gap" value="0"/>
  <prop id="maxmin/precision" value="1e-9"/>
  <prop id="smpi/async_small_thres" value="65536"/>
  <prop id="smpi/send_is_detached_thres" value="327680"/>
<!--  <prop id="smpi/os" value="1:8.75118726019245e-06:7.09598480584951e-10;1420:1.38989305424406e-05:2.18111838119125e-10;65536:0.000193970854779561:-4.82025737428887e-11;327680:0:0"/>-->
<!--  <prop id="smpi/or" value="1:9.3069771137911e-06:7.92179414036391e-10;1420:1.43097562292319e-05:8.66975835499791e-10;10000:1.41659209904282e-05:1.00877300603447e-09;65536:0:0"/>-->
<!--  <prop id="smpi/bw_factor" value="0:0.408465938;1420:0.913760459;65536:0.937794396"/>-->
<!--  <prop id="smpi/lat_factor" value="0:1.01;1420:4.02;65536:9.77"/>-->
<!--  -->
 <prop id="smpi/os" value="0:8.9300920419081e-06:7.65438202550106e-10;1420:1.39684254077781e-05:2.97409403415968e-10;32768:1.54082820250394e-05:2.44104034252286e-10;65536:0.000237866424242424:0;327680:0:0"/>
 <prop id="smpi/or" value="0:8.14025462333494e-06:8.3958813204998e-10;1420:1.26995184134793e-05:9.09218191293861e-10;32768:3.09570602567453e-05:6.95645307772806e-10;65536:0:0;327680:0:0"/>
 <prop id="smpi/bw_factor" value="0:0.400976530736138;1420:0.913555534273577;32768:1.07831886657594;65536:0.956083935262915;327680:0.929867998857892"/>
 <prop id="smpi/lat_factor" value="0:1.35489260823384;1420:3.43725032107889;32768:5.72164710873587;65536:11.9885319715471;327680:9.65041953605594"/>  
</config>
 
<AS id="AS_graphene" routing="Full" >
  <cluster id="AS_sgraphene1" prefix="graphene-" radical="1-256" suffix=".nancy.grid5000.fr"
           power="4.18E9" core="4" bw="1.25E8" lat="2.4E-5"
           sharing_policy="FULLDUPLEX" limiter_link="1.875E8" loopback_lat="1.5E-9" loopback_bw="6000000000"></cluster>
  <cluster id="AS_sgraphene2" prefix="graphene-" radical="257-512" suffix=".nancy.grid5000.fr"
           power="4.18E9" core="4" bw="1.25E8" lat="2.4E-5"
           sharing_policy="FULLDUPLEX" limiter_link="1.875E8" loopback_lat="1.5E-9" loopback_bw="6000000000"></cluster>
  <cluster id="AS_sgraphene3" prefix="graphene-" radical="513-784" suffix=".nancy.grid5000.fr"
           power="4.18E9" core="4" bw="1.25E8" lat="2.4E-5"
           sharing_policy="FULLDUPLEX" limiter_link="1.875E8" loopback_lat="1.5E-9" loopback_bw="6000000000"></cluster>
  <cluster id="AS_sgraphene4" prefix="graphene-" radical="785-1024" suffix=".nancy.grid5000.fr"
           power="4.18E9" core="4" bw="1.25E8" lat="2.4E-5"
           sharing_policy="FULLDUPLEX" limiter_link="1.875E8" loopback_lat="1.5E-9" loopback_bw="6000000000"></cluster>

  <link id="switch-backbone1" bandwidth="1162500000" latency="1.5E-6" sharing_policy="FULLDUPLEX"/>
  <link id="explicit-limiter1" bandwidth="1511250000" latency="0" sharing_policy="SHARED"/>

  <link id="switch-backbone2" bandwidth="1162500000" latency="1.5E-6" sharing_policy="FULLDUPLEX"/>
  <link id="explicit-limiter2" bandwidth="1511250000" latency="0" sharing_policy="SHARED"/>

  <link id="switch-backbone3" bandwidth="1162500000" latency="1.5E-6" sharing_policy="FULLDUPLEX"/>
  <link id="explicit-limiter3" bandwidth="1511250000" latency="0" sharing_policy="SHARED"/>

  <link id="switch-backbone4" bandwidth="1162500000" latency="1.5E-6" sharing_policy="FULLDUPLEX"/>
  <link id="explicit-limiter4" bandwidth="1511250000" latency="0" sharing_policy="SHARED"/>


     <ASroute src="AS_sgraphene1" dst="AS_sgraphene2"
         gw_src="graphene-AS_sgraphene1_router.nancy.grid5000.fr"
         gw_dst="graphene-AS_sgraphene2_router.nancy.grid5000.fr"
         symmetrical="NO"
         >
                <link_ctn id="switch-backbone1" direction="UP"/>
                <link_ctn id="explicit-limiter1"/>
                <link_ctn id="explicit-limiter2"/>
                <link_ctn id="switch-backbone2" direction="DOWN"/>
                
     </ASroute>
     <ASroute src="AS_sgraphene2" dst="AS_sgraphene1"
         gw_src="graphene-AS_sgraphene2_router.nancy.grid5000.fr"
         gw_dst="graphene-AS_sgraphene1_router.nancy.grid5000.fr"
         symmetrical="NO"
         >
                <link_ctn id="switch-backbone2" direction="UP"/>
                <link_ctn id="explicit-limiter2"/>
                <link_ctn id="explicit-limiter1"/>
                <link_ctn id="switch-backbone1" direction="DOWN"/>
     </ASroute>
     <ASroute src="AS_sgraphene2" dst="AS_sgraphene3"
         gw_src="graphene-AS_sgraphene2_router.nancy.grid5000.fr"
         gw_dst="graphene-AS_sgraphene3_router.nancy.grid5000.fr"
          symmetrical="NO"
         >
                <link_ctn id="switch-backbone2" direction="UP"/>                
                <link_ctn id="explicit-limiter2"/>
                <link_ctn id="explicit-limiter3"/>
                <link_ctn id="switch-backbone3" direction="DOWN"/>
     </ASroute>
     <ASroute src="AS_sgraphene1" dst="AS_sgraphene3"
         gw_src="graphene-AS_sgraphene1_router.nancy.grid5000.fr"
         gw_dst="graphene-AS_sgraphene3_router.nancy.grid5000.fr"
         symmetrical="NO"         
         >
                <link_ctn id="switch-backbone1" direction="UP"/>
                <link_ctn id="explicit-limiter1"/>
                <link_ctn id="explicit-limiter3"/>
                <link_ctn id="switch-backbone3" direction="DOWN"/>
     </ASroute>
          <ASroute src="AS_sgraphene3" dst="AS_sgraphene1"
         gw_src="graphene-AS_sgraphene3_router.nancy.grid5000.fr"
         gw_dst="graphene-AS_sgraphene1_router.nancy.grid5000.fr"
         symmetrical="NO"         
         >
                <link_ctn id="switch-backbone3" direction="UP"/>
                <link_ctn id="explicit-limiter3"/>
                <link_ctn id="explicit-limiter1"/>
                <link_ctn id="switch-backbone1" direction="DOWN"/>
     </ASroute>
     
          <ASroute src="AS_sgraphene1" dst="AS_sgraphene4"
         gw_src="graphene-AS_sgraphene1_router.nancy.grid5000.fr"
         gw_dst="graphene-AS_sgraphene4_router.nancy.grid5000.fr"
         symmetrical="NO"         
         >
                <link_ctn id="switch-backbone1" direction="UP"/>
                <link_ctn id="explicit-limiter1"/>
                <link_ctn id="explicit-limiter4"/>
                <link_ctn id="switch-backbone4" direction="DOWN"/>
     </ASroute>
               <ASroute src="AS_sgraphene4" dst="AS_sgraphene1"
         gw_src="graphene-AS_sgraphene4_router.nancy.grid5000.fr"
         gw_dst="graphene-AS_sgraphene1_router.nancy.grid5000.fr"
         symmetrical="NO"         
         >
                <link_ctn id="switch-backbone4" direction="UP"/>
                <link_ctn id="explicit-limiter4"/>
                <link_ctn id="explicit-limiter1"/>
                <link_ctn id="switch-backbone1" direction="DOWN"/>
     </ASroute>
          <ASroute src="AS_sgraphene2" dst="AS_sgraphene4"
         gw_src="graphene-AS_sgraphene2_router.nancy.grid5000.fr"
         gw_dst="graphene-AS_sgraphene4_router.nancy.grid5000.fr"
         symmetrical="NO"         
         >
                <link_ctn id="switch-backbone2" direction="UP"/>
                <link_ctn id="explicit-limiter2"/>
                <link_ctn id="explicit-limiter4"/>
                <link_ctn id="switch-backbone4" direction="DOWN"/>
     </ASroute>
          <ASroute src="AS_sgraphene3" dst="AS_sgraphene4"
         gw_src="graphene-AS_sgraphene3_router.nancy.grid5000.fr"
         gw_dst="graphene-AS_sgraphene4_router.nancy.grid5000.fr"
         symmetrical="NO"         
         >
                <link_ctn id="switch-backbone3" direction="UP"/>
                <link_ctn id="explicit-limiter3"/>
                <link_ctn id="explicit-limiter4"/>
                <link_ctn id="switch-backbone4" direction="DOWN"/>
     </ASroute>
              <ASroute src="AS_sgraphene4" dst="AS_sgraphene3"
         gw_src="graphene-AS_sgraphene4_router.nancy.grid5000.fr"
         gw_dst="graphene-AS_sgraphene3_router.nancy.grid5000.fr"
         symmetrical="NO"         
         >
                <link_ctn id="switch-backbone4" direction="UP"/>
                <link_ctn id="explicit-limiter4"/>
                <link_ctn id="explicit-limiter3"/>
                <link_ctn id="switch-backbone3" direction="DOWN"/>
     </ASroute>
     
               <ASroute src="AS_sgraphene3" dst="AS_sgraphene2"
         gw_src="graphene-AS_sgraphene3_router.nancy.grid5000.fr"
         gw_dst="graphene-AS_sgraphene2_router.nancy.grid5000.fr"
         symmetrical="NO"         
         >
                <link_ctn id="switch-backbone3" direction="UP"/>
                <link_ctn id="explicit-limiter3"/>
                <link_ctn id="explicit-limiter2"/>
                <link_ctn id="switch-backbone2" direction="DOWN"/>
     </ASroute>
     
                    <ASroute src="AS_sgraphene4" dst="AS_sgraphene2"
         gw_src="graphene-AS_sgraphene4_router.nancy.grid5000.fr"
         gw_dst="graphene-AS_sgraphene2_router.nancy.grid5000.fr"
         symmetrical="NO"         
         >
                <link_ctn id="switch-backbone4" direction="UP"/>
                <link_ctn id="explicit-limiter4"/>
                <link_ctn id="explicit-limiter2"/>
                <link_ctn id="switch-backbone2" direction="DOWN"/>
     </ASroute>
 </AS>
</platform>

* Experiment 1
Don't do proc:613 size:932492 as there is not enough memory (free mem: 263763200 kb)
Do proc:34 size:1596937 freemem:263763200k mem usage:108591716
** Test with algorithm 2dmesh
*** Command
#+BEGIN_EXAMPLE
smpirun -platform graphene_1024.xml -np 34 ./alltoall 1596937 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:2dmesh --cfg=maxmin/precision:1e-7
#+END_EXAMPLE
*** raw stdout
#+BEGIN_EXAMPLE
simTime:10.982843 Success numproc=34 msgsize=1596937
#+END_EXAMPLE
*** raw stderr
#+BEGIN_EXAMPLE
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/TCP_gamma' to '4194304'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/running_power' to '20000'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/alltoall' to '2dmesh'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'maxmin/precision' to '1e-7'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/bw_factor' to '0:0.400976530736138;1420:0.913555534273577;32768:1.07831886657594;65536:0.956083935262915;327680:0.929867998857892'
[0.000000] [surf_parse/INFO] The custom configuration 'network/TCP_gamma' is already defined by user!
[0.000000] [surf_parse/INFO] The custom configuration 'maxmin/precision' is already defined by user!
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/or' to '0:8.14025462333494e-06:8.3958813204998e-10;1420:1.26995184134793e-05:9.09218191293861e-10;32768:3.09570602567453e-05:6.95645307772806e-10;65536:0:0;327680:0:0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/os' to '0:8.9300920419081e-06:7.65438202550106e-10;1420:1.39684254077781e-05:2.97409403415968e-10;32768:1.54082820250394e-05:2.44104034252286e-10;65536:0.000237866424242424:0;327680:0:0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/sender_gap' to '0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/send_is_detached_thres' to '327680'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'workstation/model' to 'compound'
[0.000000] [surf_parse/INFO] The custom configuration 'network/model' is already defined by user!
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/async_small_thres' to '65536'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/lat_factor' to '0:1.35489260823384;1420:3.43725032107889;32768:5.72164710873587;65536:11.9885319715471;327680:9.65041953605594'
rm: cannot remove `tmphostsi0JbO': No such file or directory
rm: cannot remove `tmpiJM0Kq': No such file or directory

#+END_EXAMPLE
*** raw timing information
#+BEGIN_EXAMPLE
clock:30.73 user:13.76 sys:16.47 swapped:0 exitval:0 max:10667292k

#+END_EXAMPLE
*** Result
PRECIOUS_RESULT algo:2dmesh numproc:34 msgsize:1596937 hostTime:30.73 hostMem:10667292k simTime:10.982843 
** Test with algorithm 3dmesh
*** Command
#+BEGIN_EXAMPLE
smpirun -platform graphene_1024.xml -np 34 ./alltoall 1596937 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:3dmesh --cfg=maxmin/precision:1e-7
#+END_EXAMPLE
*** raw stdout
#+BEGIN_EXAMPLE
[0.000000] all_to_all returned 12
#+END_EXAMPLE
*** raw stderr
#+BEGIN_EXAMPLE
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/TCP_gamma' to '4194304'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/running_power' to '20000'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/alltoall' to '3dmesh'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'maxmin/precision' to '1e-7'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/bw_factor' to '0:0.400976530736138;1420:0.913555534273577;32768:1.07831886657594;65536:0.956083935262915;327680:0.929867998857892'
[0.000000] [surf_parse/INFO] The custom configuration 'network/TCP_gamma' is already defined by user!
[0.000000] [surf_parse/INFO] The custom configuration 'maxmin/precision' is already defined by user!
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/or' to '0:8.14025462333494e-06:8.3958813204998e-10;1420:1.26995184134793e-05:9.09218191293861e-10;32768:3.09570602567453e-05:6.95645307772806e-10;65536:0:0;327680:0:0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/os' to '0:8.9300920419081e-06:7.65438202550106e-10;1420:1.39684254077781e-05:2.97409403415968e-10;32768:1.54082820250394e-05:2.44104034252286e-10;65536:0.000237866424242424:0;327680:0:0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/sender_gap' to '0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/send_is_detached_thres' to '327680'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'workstation/model' to 'compound'
[0.000000] [surf_parse/INFO] The custom configuration 'network/model' is already defined by user!
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/async_small_thres' to '65536'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/lat_factor' to '0:1.35489260823384;1420:3.43725032107889;32768:5.72164710873587;65536:11.9885319715471;327680:9.65041953605594'
[0.000000] /home/mquinson/Code/simgrid/src/simix/smx_global.c:463: [simix_kernel/CRITICAL] Oops ! Deadlock or code not perfectly clean.
[0.000000] [simix_kernel/INFO] 33 processes are still running, waiting for something.
[0.000000] [simix_kernel/INFO] Legend of the following listing: "Process <pid> (<name>@<host>): <status>"
[0.000000] [simix_kernel/INFO] Process 2 (1@graphene-2.nancy.grid5000.fr): waiting for synchronization synchro 0xceb860 (synchro) in state 0 to finish
[0.000000] [simix_kernel/INFO] Process 3 (2@graphene-3.nancy.grid5000.fr): waiting for synchronization synchro 0xceac30 (synchro) in state 0 to finish
[0.000000] [simix_kernel/INFO] Process 4 (3@graphene-4.nancy.grid5000.fr): waiting for synchronization synchro 0xceb950 (synchro) in state 0 to finish
[0.000000] [simix_kernel/INFO] Process 5 (4@graphene-5.nancy.grid5000.fr): waiting for synchronization synchro 0xceaff0 (synchro) in state 0 to finish
[0.000000] [simix_kernel/INFO] Process 6 (5@graphene-6.nancy.grid5000.fr): waiting for synchronization synchro 0xceab40 (synchro) in state 0 to finish
[0.000000] [simix_kernel/INFO] Process 7 (6@graphene-7.nancy.grid5000.fr): waiting for synchronization synchro 0xceb770 (synchro) in state 0 to finish
[0.000000] [simix_kernel/INFO] Process 8 (7@graphene-8.nancy.grid5000.fr): waiting for synchronization synchro 0xceb3b0 (synchro) in state 0 to finish
[0.000000] [simix_kernel/INFO] Process 9 (8@graphene-9.nancy.grid5000.fr): waiting for synchronization synchro 0xceae10 (synchro) in state 0 to finish
[0.000000] [simix_kernel/INFO] Process 10 (9@graphene-10.nancy.grid5000.fr): waiting for synchronization synchro 0xceb680 (synchro) in state 0 to finish
[0.000000] [simix_kernel/INFO] Process 11 (10@graphene-11.nancy.grid5000.fr): waiting for synchronization synchro 0xceaf00 (synchro) in state 0 to finish
[0.000000] [simix_kernel/INFO] Process 12 (11@graphene-12.nancy.grid5000.fr): waiting for synchronization synchro 0xceba40 (synchro) in state 0 to finish
[0.000000] [simix_kernel/INFO] Process 13 (12@graphene-13.nancy.grid5000.fr): waiting for synchronization synchro 0xceb0e0 (synchro) in state 0 to finish
[0.000000] [simix_kernel/INFO] Process 14 (13@graphene-14.nancy.grid5000.fr): waiting for synchronization synchro 0xcead20 (synchro) in state 0 to finish
[0.000000] [simix_kernel/INFO] Process 15 (14@graphene-15.nancy.grid5000.fr): waiting for synchronization synchro 0xcebb30 (synchro) in state 0 to finish
[0.000000] [simix_kernel/INFO] Process 16 (15@graphene-16.nancy.grid5000.fr): waiting for synchronization synchro 0xceb590 (synchro) in state 0 to finish
[0.000000] [simix_kernel/INFO] Process 17 (16@graphene-17.nancy.grid5000.fr): waiting for synchronization synchro 0xceb1d0 (synchro) in state 0 to finish
[0.000000] [simix_kernel/INFO] Process 18 (17@graphene-18.nancy.grid5000.fr): waiting for synchronization synchro 0xceb2c0 (synchro) in state 0 to finish
[0.000000] [simix_kernel/INFO] Process 19 (18@graphene-19.nancy.grid5000.fr): waiting for synchronization synchro 0xcea960 (synchro) in state 0 to finish
[0.000000] [simix_kernel/INFO] Process 20 (19@graphene-20.nancy.grid5000.fr): waiting for synchronization synchro 0xceb4a0 (synchro) in state 0 to finish
[0.000000] [simix_kernel/INFO] Process 21 (20@graphene-21.nancy.grid5000.fr): waiting for synchronization synchro 0xceaa50 (synchro) in state 0 to finish
[0.000000] [simix_kernel/INFO] Process 22 (21@graphene-22.nancy.grid5000.fr): waiting for synchronization synchro 0xcea870 (synchro) in state 0 to finish
[0.000000] [simix_kernel/INFO] Process 23 (22@graphene-23.nancy.grid5000.fr): waiting for synchronization synchro 0xcea4b0 (synchro) in state 0 to finish
[0.000000] [simix_kernel/INFO] Process 24 (23@graphene-24.nancy.grid5000.fr): waiting for synchronization synchro 0xcea2d0 (synchro) in state 0 to finish
[0.000000] [simix_kernel/INFO] Process 25 (24@graphene-25.nancy.grid5000.fr): waiting for synchronization synchro 0xcea000 (synchro) in state 0 to finish
[0.000000] [simix_kernel/INFO] Process 26 (25@graphene-26.nancy.grid5000.fr): waiting for synchronization synchro 0xce9d30 (synchro) in state 0 to finish
[0.000000] [simix_kernel/INFO] Process 27 (26@graphene-27.nancy.grid5000.fr): waiting for synchronization synchro 0xce9f10 (synchro) in state 0 to finish
[0.000000] [simix_kernel/INFO] Process 28 (27@graphene-28.nancy.grid5000.fr): waiting for synchronization synchro 0xcea5a0 (synchro) in state 0 to finish
[0.000000] [simix_kernel/INFO] Process 29 (28@graphene-29.nancy.grid5000.fr): waiting for synchronization synchro 0xcea0f0 (synchro) in state 0 to finish
[0.000000] [simix_kernel/INFO] Process 30 (29@graphene-30.nancy.grid5000.fr): waiting for synchronization synchro 0xce9e20 (synchro) in state 0 to finish
[0.000000] [simix_kernel/INFO] Process 31 (30@graphene-31.nancy.grid5000.fr): waiting for synchronization synchro 0xcea1e0 (synchro) in state 0 to finish
[0.000000] [simix_kernel/INFO] Process 32 (31@graphene-32.nancy.grid5000.fr): waiting for synchronization synchro 0xcea780 (synchro) in state 0 to finish
[0.000000] [simix_kernel/INFO] Process 33 (32@graphene-33.nancy.grid5000.fr): waiting for synchronization synchro 0xcea3c0 (synchro) in state 0 to finish
[0.000000] [simix_kernel/INFO] Process 34 (33@graphene-34.nancy.grid5000.fr): waiting for synchronization synchro 0xcea690 (synchro) in state 0 to finish
/home/mquinson/simgrid-3.12/bin/smpirun: line 461:  5281 Aborted                 ${EXEC} ${TRACEOPTIONS} ${SIMOPTS} ${PLATFORMTMP} ${APPLICATIONTMP}

#+END_EXAMPLE
*** raw timing information
#+BEGIN_EXAMPLE
Command exited with non-zero status 134
clock:2.11 user:1.04 sys:0.67 swapped:0 exitval:134 max:1811784k

#+END_EXAMPLE
*** Result
FAILED_RESULT: non-zero status (algo:3dmesh numproc:34 msgsize:1596937 hostTime:2.11 hostMem:1811784k)
** Test with algorithm basic_linear
*** Command
#+BEGIN_EXAMPLE
smpirun -platform graphene_1024.xml -np 34 ./alltoall 1596937 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:basic_linear --cfg=maxmin/precision:1e-7
#+END_EXAMPLE
*** raw stdout
#+BEGIN_EXAMPLE
simTime:0.562585 Success numproc=34 msgsize=1596937
#+END_EXAMPLE
*** raw stderr
#+BEGIN_EXAMPLE
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/TCP_gamma' to '4194304'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/running_power' to '20000'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/alltoall' to 'basic_linear'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'maxmin/precision' to '1e-7'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/bw_factor' to '0:0.400976530736138;1420:0.913555534273577;32768:1.07831886657594;65536:0.956083935262915;327680:0.929867998857892'
[0.000000] [surf_parse/INFO] The custom configuration 'network/TCP_gamma' is already defined by user!
[0.000000] [surf_parse/INFO] The custom configuration 'maxmin/precision' is already defined by user!
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/or' to '0:8.14025462333494e-06:8.3958813204998e-10;1420:1.26995184134793e-05:9.09218191293861e-10;32768:3.09570602567453e-05:6.95645307772806e-10;65536:0:0;327680:0:0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/os' to '0:8.9300920419081e-06:7.65438202550106e-10;1420:1.39684254077781e-05:2.97409403415968e-10;32768:1.54082820250394e-05:2.44104034252286e-10;65536:0.000237866424242424:0;327680:0:0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/sender_gap' to '0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/send_is_detached_thres' to '327680'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'workstation/model' to 'compound'
[0.000000] [surf_parse/INFO] The custom configuration 'network/model' is already defined by user!
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/async_small_thres' to '65536'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/lat_factor' to '0:1.35489260823384;1420:3.43725032107889;32768:5.72164710873587;65536:11.9885319715471;327680:9.65041953605594'

#+END_EXAMPLE
*** raw timing information
#+BEGIN_EXAMPLE
clock:2.63 user:1.64 sys:0.60 swapped:0 exitval:0 max:1813636k

#+END_EXAMPLE
*** Result
PRECIOUS_RESULT algo:basic_linear numproc:34 msgsize:1596937 hostTime:2.63 hostMem:1813636k simTime:0.562585 
** Test with algorithm bruck
*** Command
#+BEGIN_EXAMPLE
smpirun -platform graphene_1024.xml -np 34 ./alltoall 1596937 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:bruck --cfg=maxmin/precision:1e-7
#+END_EXAMPLE
*** raw stdout
#+BEGIN_EXAMPLE
simTime:0.562585 Success numproc=34 msgsize=1596937
#+END_EXAMPLE
*** raw stderr
#+BEGIN_EXAMPLE
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/TCP_gamma' to '4194304'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/running_power' to '20000'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/alltoall' to 'bruck'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'maxmin/precision' to '1e-7'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/bw_factor' to '0:0.400976530736138;1420:0.913555534273577;32768:1.07831886657594;65536:0.956083935262915;327680:0.929867998857892'
[0.000000] [surf_parse/INFO] The custom configuration 'network/TCP_gamma' is already defined by user!
[0.000000] [surf_parse/INFO] The custom configuration 'maxmin/precision' is already defined by user!
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/or' to '0:8.14025462333494e-06:8.3958813204998e-10;1420:1.26995184134793e-05:9.09218191293861e-10;32768:3.09570602567453e-05:6.95645307772806e-10;65536:0:0;327680:0:0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/os' to '0:8.9300920419081e-06:7.65438202550106e-10;1420:1.39684254077781e-05:2.97409403415968e-10;32768:1.54082820250394e-05:2.44104034252286e-10;65536:0.000237866424242424:0;327680:0:0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/sender_gap' to '0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/send_is_detached_thres' to '327680'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'workstation/model' to 'compound'
[0.000000] [surf_parse/INFO] The custom configuration 'network/model' is already defined by user!
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/async_small_thres' to '65536'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/lat_factor' to '0:1.35489260823384;1420:3.43725032107889;32768:5.72164710873587;65536:11.9885319715471;327680:9.65041953605594'

#+END_EXAMPLE
*** raw timing information
#+BEGIN_EXAMPLE
clock:2.65 user:1.60 sys:0.66 swapped:0 exitval:0 max:1813900k

#+END_EXAMPLE
*** Result
PRECIOUS_RESULT algo:bruck numproc:34 msgsize:1596937 hostTime:2.65 hostMem:1813900k simTime:0.562585 
** Test with algorithm pair
*** Command
#+BEGIN_EXAMPLE
smpirun -platform graphene_1024.xml -np 34 ./alltoall 1596937 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:pair --cfg=maxmin/precision:1e-7
#+END_EXAMPLE
*** raw stdout
#+BEGIN_EXAMPLE

#+END_EXAMPLE
*** raw stderr
#+BEGIN_EXAMPLE
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/TCP_gamma' to '4194304'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/running_power' to '20000'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/alltoall' to 'pair'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'maxmin/precision' to '1e-7'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/bw_factor' to '0:0.400976530736138;1420:0.913555534273577;32768:1.07831886657594;65536:0.956083935262915;327680:0.929867998857892'
[0.000000] [surf_parse/INFO] The custom configuration 'network/TCP_gamma' is already defined by user!
[0.000000] [surf_parse/INFO] The custom configuration 'maxmin/precision' is already defined by user!
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/or' to '0:8.14025462333494e-06:8.3958813204998e-10;1420:1.26995184134793e-05:9.09218191293861e-10;32768:3.09570602567453e-05:6.95645307772806e-10;65536:0:0;327680:0:0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/os' to '0:8.9300920419081e-06:7.65438202550106e-10;1420:1.39684254077781e-05:2.97409403415968e-10;32768:1.54082820250394e-05:2.44104034252286e-10;65536:0.000237866424242424:0;327680:0:0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/sender_gap' to '0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/send_is_detached_thres' to '327680'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'workstation/model' to 'compound'
[0.000000] [surf_parse/INFO] The custom configuration 'network/model' is already defined by user!
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/async_small_thres' to '65536'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/lat_factor' to '0:1.35489260823384;1420:3.43725032107889;32768:5.72164710873587;65536:11.9885319715471;327680:9.65041953605594'
** SimGrid: UNCAUGHT EXCEPTION received on ./alltoall(0): category: invalid argument; value: 0
** alltoall pair algorithm can't be used with non power of two number of processes ! 
** Thrown by 31() in this process
[graphene-32.nancy.grid5000.fr:31:(0) 0.000000] /home/mquinson/Code/simgrid/src/xbt/ex.c:146: [xbt_ex/CRITICAL] alltoall pair algorithm can't be used with non power of two number of processes ! 

**   In smpi_coll_tuned_alltoall_pair() at /home/mquinson/Code/simgrid/src/smpi/colls/alltoall-pair.c:82
**   In PMPI_Alltoall() at /home/mquinson/Code/simgrid/src/smpi/smpi_pmpi.c:2424
**   In smpi_simulated_main_() at ??:0
**   In smx_ctx_raw_stop() at /home/mquinson/Code/simgrid/src/simix/smx_context_raw.c:402
/home/mquinson/simgrid-3.12/bin/smpirun: line 461:  6012 Aborted                 ${EXEC} ${TRACEOPTIONS} ${SIMOPTS} ${PLATFORMTMP} ${APPLICATIONTMP}

#+END_EXAMPLE
*** raw timing information
#+BEGIN_EXAMPLE
Command exited with non-zero status 134
clock:2.23 user:1.11 sys:0.67 swapped:0 exitval:134 max:1812176k

#+END_EXAMPLE
*** Result
FAILED_RESULT: non-zero status (algo:pair numproc:34 msgsize:1596937 hostTime:2.23 hostMem:1812176k)
** Test with algorithm rdb
*** Command
#+BEGIN_EXAMPLE
smpirun -platform graphene_1024.xml -np 34 ./alltoall 1596937 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:rdb --cfg=maxmin/precision:1e-7
#+END_EXAMPLE
*** raw stdout
#+BEGIN_EXAMPLE
simTime:36.867618 Success numproc=34 msgsize=1596937
#+END_EXAMPLE
*** raw stderr
#+BEGIN_EXAMPLE
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/TCP_gamma' to '4194304'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/running_power' to '20000'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/alltoall' to 'rdb'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'maxmin/precision' to '1e-7'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/bw_factor' to '0:0.400976530736138;1420:0.913555534273577;32768:1.07831886657594;65536:0.956083935262915;327680:0.929867998857892'
[0.000000] [surf_parse/INFO] The custom configuration 'network/TCP_gamma' is already defined by user!
[0.000000] [surf_parse/INFO] The custom configuration 'maxmin/precision' is already defined by user!
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/or' to '0:8.14025462333494e-06:8.3958813204998e-10;1420:1.26995184134793e-05:9.09218191293861e-10;32768:3.09570602567453e-05:6.95645307772806e-10;65536:0:0;327680:0:0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/os' to '0:8.9300920419081e-06:7.65438202550106e-10;1420:1.39684254077781e-05:2.97409403415968e-10;32768:1.54082820250394e-05:2.44104034252286e-10;65536:0.000237866424242424:0;327680:0:0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/sender_gap' to '0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/send_is_detached_thres' to '327680'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'workstation/model' to 'compound'
[0.000000] [surf_parse/INFO] The custom configuration 'network/model' is already defined by user!
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/async_small_thres' to '65536'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/lat_factor' to '0:1.35489260823384;1420:3.43725032107889;32768:5.72164710873587;65536:11.9885319715471;327680:9.65041953605594'

#+END_EXAMPLE
*** raw timing information
#+BEGIN_EXAMPLE
clock:59.58 user:26.88 sys:32.18 swapped:0 exitval:0 max:59925848k

#+END_EXAMPLE
*** Result
PRECIOUS_RESULT algo:rdb numproc:34 msgsize:1596937 hostTime:59.58 hostMem:59925848k simTime:36.867618 
** Test with algorithm ring
*** Command
#+BEGIN_EXAMPLE
smpirun -platform graphene_1024.xml -np 34 ./alltoall 1596937 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:ring --cfg=maxmin/precision:1e-7
#+END_EXAMPLE
*** raw stdout
#+BEGIN_EXAMPLE
simTime:0.577408 Success numproc=34 msgsize=1596937
#+END_EXAMPLE
*** raw stderr
#+BEGIN_EXAMPLE
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/TCP_gamma' to '4194304'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/running_power' to '20000'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/alltoall' to 'ring'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'maxmin/precision' to '1e-7'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/bw_factor' to '0:0.400976530736138;1420:0.913555534273577;32768:1.07831886657594;65536:0.956083935262915;327680:0.929867998857892'
[0.000000] [surf_parse/INFO] The custom configuration 'network/TCP_gamma' is already defined by user!
[0.000000] [surf_parse/INFO] The custom configuration 'maxmin/precision' is already defined by user!
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/or' to '0:8.14025462333494e-06:8.3958813204998e-10;1420:1.26995184134793e-05:9.09218191293861e-10;32768:3.09570602567453e-05:6.95645307772806e-10;65536:0:0;327680:0:0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/os' to '0:8.9300920419081e-06:7.65438202550106e-10;1420:1.39684254077781e-05:2.97409403415968e-10;32768:1.54082820250394e-05:2.44104034252286e-10;65536:0.000237866424242424:0;327680:0:0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/sender_gap' to '0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/send_is_detached_thres' to '327680'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'workstation/model' to 'compound'
[0.000000] [surf_parse/INFO] The custom configuration 'network/model' is already defined by user!
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/async_small_thres' to '65536'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/lat_factor' to '0:1.35489260823384;1420:3.43725032107889;32768:5.72164710873587;65536:11.9885319715471;327680:9.65041953605594'

#+END_EXAMPLE
*** raw timing information
#+BEGIN_EXAMPLE
clock:2.77 user:1.68 sys:0.68 swapped:0 exitval:0 max:1812312k

#+END_EXAMPLE
*** Result
PRECIOUS_RESULT algo:ring numproc:34 msgsize:1596937 hostTime:2.77 hostMem:1812312k simTime:0.577408 
** Test with algorithm ring_light_barrier
*** Command
#+BEGIN_EXAMPLE
smpirun -platform graphene_1024.xml -np 34 ./alltoall 1596937 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:ring_light_barrier --cfg=maxmin/precision:1e-7
#+END_EXAMPLE
*** raw stdout
#+BEGIN_EXAMPLE
simTime:0.579490 Success numproc=34 msgsize=1596937
#+END_EXAMPLE
*** raw stderr
#+BEGIN_EXAMPLE
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/TCP_gamma' to '4194304'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/running_power' to '20000'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/alltoall' to 'ring_light_barrier'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'maxmin/precision' to '1e-7'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/bw_factor' to '0:0.400976530736138;1420:0.913555534273577;32768:1.07831886657594;65536:0.956083935262915;327680:0.929867998857892'
[0.000000] [surf_parse/INFO] The custom configuration 'network/TCP_gamma' is already defined by user!
[0.000000] [surf_parse/INFO] The custom configuration 'maxmin/precision' is already defined by user!
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/or' to '0:8.14025462333494e-06:8.3958813204998e-10;1420:1.26995184134793e-05:9.09218191293861e-10;32768:3.09570602567453e-05:6.95645307772806e-10;65536:0:0;327680:0:0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/os' to '0:8.9300920419081e-06:7.65438202550106e-10;1420:1.39684254077781e-05:2.97409403415968e-10;32768:1.54082820250394e-05:2.44104034252286e-10;65536:0.000237866424242424:0;327680:0:0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/sender_gap' to '0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/send_is_detached_thres' to '327680'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'workstation/model' to 'compound'
[0.000000] [surf_parse/INFO] The custom configuration 'network/model' is already defined by user!
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/async_small_thres' to '65536'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/lat_factor' to '0:1.35489260823384;1420:3.43725032107889;32768:5.72164710873587;65536:11.9885319715471;327680:9.65041953605594'

#+END_EXAMPLE
*** raw timing information
#+BEGIN_EXAMPLE
clock:2.71 user:1.72 sys:0.67 swapped:0 exitval:0 max:1812316k

#+END_EXAMPLE
*** Result
PRECIOUS_RESULT algo:ring_light_barrier numproc:34 msgsize:1596937 hostTime:2.71 hostMem:1812316k simTime:0.579490 
** Test with algorithm ring_mpi_barrier
*** Command
#+BEGIN_EXAMPLE
smpirun -platform graphene_1024.xml -np 34 ./alltoall 1596937 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:ring_mpi_barrier --cfg=maxmin/precision:1e-7
#+END_EXAMPLE
*** raw stdout
#+BEGIN_EXAMPLE
simTime:0.586062 Success numproc=34 msgsize=1596937
#+END_EXAMPLE
*** raw stderr
#+BEGIN_EXAMPLE
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/TCP_gamma' to '4194304'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/running_power' to '20000'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/alltoall' to 'ring_mpi_barrier'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'maxmin/precision' to '1e-7'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/bw_factor' to '0:0.400976530736138;1420:0.913555534273577;32768:1.07831886657594;65536:0.956083935262915;327680:0.929867998857892'
[0.000000] [surf_parse/INFO] The custom configuration 'network/TCP_gamma' is already defined by user!
[0.000000] [surf_parse/INFO] The custom configuration 'maxmin/precision' is already defined by user!
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/or' to '0:8.14025462333494e-06:8.3958813204998e-10;1420:1.26995184134793e-05:9.09218191293861e-10;32768:3.09570602567453e-05:6.95645307772806e-10;65536:0:0;327680:0:0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/os' to '0:8.9300920419081e-06:7.65438202550106e-10;1420:1.39684254077781e-05:2.97409403415968e-10;32768:1.54082820250394e-05:2.44104034252286e-10;65536:0.000237866424242424:0;327680:0:0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/sender_gap' to '0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/send_is_detached_thres' to '327680'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'workstation/model' to 'compound'
[0.000000] [surf_parse/INFO] The custom configuration 'network/model' is already defined by user!
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/async_small_thres' to '65536'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/lat_factor' to '0:1.35489260823384;1420:3.43725032107889;32768:5.72164710873587;65536:11.9885319715471;327680:9.65041953605594'

#+END_EXAMPLE
*** raw timing information
#+BEGIN_EXAMPLE
clock:2.77 user:1.60 sys:0.75 swapped:0 exitval:0 max:1812316k

#+END_EXAMPLE
*** Result
PRECIOUS_RESULT algo:ring_mpi_barrier numproc:34 msgsize:1596937 hostTime:2.77 hostMem:1812316k simTime:0.586062 
** Test with algorithm ring_one_barrier
*** Command
#+BEGIN_EXAMPLE
smpirun -platform graphene_1024.xml -np 34 ./alltoall 1596937 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:ring_one_barrier --cfg=maxmin/precision:1e-7
#+END_EXAMPLE
*** raw stdout
#+BEGIN_EXAMPLE
simTime:0.577669 Success numproc=34 msgsize=1596937
#+END_EXAMPLE
*** raw stderr
#+BEGIN_EXAMPLE
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/TCP_gamma' to '4194304'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/running_power' to '20000'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/alltoall' to 'ring_one_barrier'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'maxmin/precision' to '1e-7'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/bw_factor' to '0:0.400976530736138;1420:0.913555534273577;32768:1.07831886657594;65536:0.956083935262915;327680:0.929867998857892'
[0.000000] [surf_parse/INFO] The custom configuration 'network/TCP_gamma' is already defined by user!
[0.000000] [surf_parse/INFO] The custom configuration 'maxmin/precision' is already defined by user!
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/or' to '0:8.14025462333494e-06:8.3958813204998e-10;1420:1.26995184134793e-05:9.09218191293861e-10;32768:3.09570602567453e-05:6.95645307772806e-10;65536:0:0;327680:0:0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/os' to '0:8.9300920419081e-06:7.65438202550106e-10;1420:1.39684254077781e-05:2.97409403415968e-10;32768:1.54082820250394e-05:2.44104034252286e-10;65536:0.000237866424242424:0;327680:0:0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/sender_gap' to '0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/send_is_detached_thres' to '327680'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'workstation/model' to 'compound'
[0.000000] [surf_parse/INFO] The custom configuration 'network/model' is already defined by user!
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/async_small_thres' to '65536'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/lat_factor' to '0:1.35489260823384;1420:3.43725032107889;32768:5.72164710873587;65536:11.9885319715471;327680:9.65041953605594'

#+END_EXAMPLE
*** raw timing information
#+BEGIN_EXAMPLE
clock:2.63 user:1.59 sys:0.64 swapped:0 exitval:0 max:1812316k

#+END_EXAMPLE
*** Result
PRECIOUS_RESULT algo:ring_one_barrier numproc:34 msgsize:1596937 hostTime:2.63 hostMem:1812316k simTime:0.577669 
** Test with algorithm mvapich2_scatter_dest
*** Command
#+BEGIN_EXAMPLE
smpirun -platform graphene_1024.xml -np 34 ./alltoall 1596937 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:mvapich2_scatter_dest --cfg=maxmin/precision:1e-7
#+END_EXAMPLE
*** raw stdout
#+BEGIN_EXAMPLE
simTime:0.566291 Success numproc=34 msgsize=1596937
#+END_EXAMPLE
*** raw stderr
#+BEGIN_EXAMPLE
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/TCP_gamma' to '4194304'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/running_power' to '20000'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/alltoall' to 'mvapich2_scatter_dest'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'maxmin/precision' to '1e-7'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/bw_factor' to '0:0.400976530736138;1420:0.913555534273577;32768:1.07831886657594;65536:0.956083935262915;327680:0.929867998857892'
[0.000000] [surf_parse/INFO] The custom configuration 'network/TCP_gamma' is already defined by user!
[0.000000] [surf_parse/INFO] The custom configuration 'maxmin/precision' is already defined by user!
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/or' to '0:8.14025462333494e-06:8.3958813204998e-10;1420:1.26995184134793e-05:9.09218191293861e-10;32768:3.09570602567453e-05:6.95645307772806e-10;65536:0:0;327680:0:0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/os' to '0:8.9300920419081e-06:7.65438202550106e-10;1420:1.39684254077781e-05:2.97409403415968e-10;32768:1.54082820250394e-05:2.44104034252286e-10;65536:0.000237866424242424:0;327680:0:0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/sender_gap' to '0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/send_is_detached_thres' to '327680'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'workstation/model' to 'compound'
[0.000000] [surf_parse/INFO] The custom configuration 'network/model' is already defined by user!
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/async_small_thres' to '65536'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/lat_factor' to '0:1.35489260823384;1420:3.43725032107889;32768:5.72164710873587;65536:11.9885319715471;327680:9.65041953605594'

#+END_EXAMPLE
*** raw timing information
#+BEGIN_EXAMPLE
clock:2.80 user:1.68 sys:0.70 swapped:0 exitval:0 max:1812316k

#+END_EXAMPLE
*** Result
PRECIOUS_RESULT algo:mvapich2_scatter_dest numproc:34 msgsize:1596937 hostTime:2.80 hostMem:1812316k simTime:0.566291 
** Test with algorithm mvapich2
*** Command
#+BEGIN_EXAMPLE
smpirun -platform graphene_1024.xml -np 34 ./alltoall 1596937 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:mvapich2 --cfg=maxmin/precision:1e-7
#+END_EXAMPLE
*** raw stdout
#+BEGIN_EXAMPLE
simTime:0.566291 Success numproc=34 msgsize=1596937
#+END_EXAMPLE
*** raw stderr
#+BEGIN_EXAMPLE
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/TCP_gamma' to '4194304'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/running_power' to '20000'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/alltoall' to 'mvapich2'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'maxmin/precision' to '1e-7'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/bw_factor' to '0:0.400976530736138;1420:0.913555534273577;32768:1.07831886657594;65536:0.956083935262915;327680:0.929867998857892'
[0.000000] [surf_parse/INFO] The custom configuration 'network/TCP_gamma' is already defined by user!
[0.000000] [surf_parse/INFO] The custom configuration 'maxmin/precision' is already defined by user!
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/or' to '0:8.14025462333494e-06:8.3958813204998e-10;1420:1.26995184134793e-05:9.09218191293861e-10;32768:3.09570602567453e-05:6.95645307772806e-10;65536:0:0;327680:0:0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/os' to '0:8.9300920419081e-06:7.65438202550106e-10;1420:1.39684254077781e-05:2.97409403415968e-10;32768:1.54082820250394e-05:2.44104034252286e-10;65536:0.000237866424242424:0;327680:0:0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/sender_gap' to '0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/send_is_detached_thres' to '327680'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'workstation/model' to 'compound'
[0.000000] [surf_parse/INFO] The custom configuration 'network/model' is already defined by user!
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/async_small_thres' to '65536'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/lat_factor' to '0:1.35489260823384;1420:3.43725032107889;32768:5.72164710873587;65536:11.9885319715471;327680:9.65041953605594'

#+END_EXAMPLE
*** raw timing information
#+BEGIN_EXAMPLE
clock:2.68 user:1.76 sys:0.59 swapped:0 exitval:0 max:1812320k

#+END_EXAMPLE
*** Result
PRECIOUS_RESULT algo:mvapich2 numproc:34 msgsize:1596937 hostTime:2.68 hostMem:1812320k simTime:0.566291 
** Test with algorithm ompi
*** Command
#+BEGIN_EXAMPLE
smpirun -platform graphene_1024.xml -np 34 ./alltoall 1596937 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:ompi --cfg=maxmin/precision:1e-7
#+END_EXAMPLE
*** raw stdout
#+BEGIN_EXAMPLE
simTime:0.577408 Success numproc=34 msgsize=1596937
#+END_EXAMPLE
*** raw stderr
#+BEGIN_EXAMPLE
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/TCP_gamma' to '4194304'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/running_power' to '20000'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/alltoall' to 'ompi'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'maxmin/precision' to '1e-7'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/bw_factor' to '0:0.400976530736138;1420:0.913555534273577;32768:1.07831886657594;65536:0.956083935262915;327680:0.929867998857892'
[0.000000] [surf_parse/INFO] The custom configuration 'network/TCP_gamma' is already defined by user!
[0.000000] [surf_parse/INFO] The custom configuration 'maxmin/precision' is already defined by user!
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/or' to '0:8.14025462333494e-06:8.3958813204998e-10;1420:1.26995184134793e-05:9.09218191293861e-10;32768:3.09570602567453e-05:6.95645307772806e-10;65536:0:0;327680:0:0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/os' to '0:8.9300920419081e-06:7.65438202550106e-10;1420:1.39684254077781e-05:2.97409403415968e-10;32768:1.54082820250394e-05:2.44104034252286e-10;65536:0.000237866424242424:0;327680:0:0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/sender_gap' to '0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/send_is_detached_thres' to '327680'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'workstation/model' to 'compound'
[0.000000] [surf_parse/INFO] The custom configuration 'network/model' is already defined by user!
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/async_small_thres' to '65536'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/lat_factor' to '0:1.35489260823384;1420:3.43725032107889;32768:5.72164710873587;65536:11.9885319715471;327680:9.65041953605594'

#+END_EXAMPLE
*** raw timing information
#+BEGIN_EXAMPLE
clock:2.50 user:1.47 sys:0.63 swapped:0 exitval:0 max:1812316k

#+END_EXAMPLE
*** Result
PRECIOUS_RESULT algo:ompi numproc:34 msgsize:1596937 hostTime:2.50 hostMem:1812316k simTime:0.577408 
** Test with algorithm mpich
*** Command
#+BEGIN_EXAMPLE
smpirun -platform graphene_1024.xml -np 34 ./alltoall 1596937 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:mpich --cfg=maxmin/precision:1e-7
#+END_EXAMPLE
*** raw stdout
#+BEGIN_EXAMPLE
simTime:0.577408 Success numproc=34 msgsize=1596937
#+END_EXAMPLE
*** raw stderr
#+BEGIN_EXAMPLE
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/TCP_gamma' to '4194304'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/running_power' to '20000'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/alltoall' to 'mpich'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'maxmin/precision' to '1e-7'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/bw_factor' to '0:0.400976530736138;1420:0.913555534273577;32768:1.07831886657594;65536:0.956083935262915;327680:0.929867998857892'
[0.000000] [surf_parse/INFO] The custom configuration 'network/TCP_gamma' is already defined by user!
[0.000000] [surf_parse/INFO] The custom configuration 'maxmin/precision' is already defined by user!
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/or' to '0:8.14025462333494e-06:8.3958813204998e-10;1420:1.26995184134793e-05:9.09218191293861e-10;32768:3.09570602567453e-05:6.95645307772806e-10;65536:0:0;327680:0:0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/os' to '0:8.9300920419081e-06:7.65438202550106e-10;1420:1.39684254077781e-05:2.97409403415968e-10;32768:1.54082820250394e-05:2.44104034252286e-10;65536:0.000237866424242424:0;327680:0:0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/sender_gap' to '0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/send_is_detached_thres' to '327680'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'workstation/model' to 'compound'
[0.000000] [surf_parse/INFO] The custom configuration 'network/model' is already defined by user!
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/async_small_thres' to '65536'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/lat_factor' to '0:1.35489260823384;1420:3.43725032107889;32768:5.72164710873587;65536:11.9885319715471;327680:9.65041953605594'

#+END_EXAMPLE
*** raw timing information
#+BEGIN_EXAMPLE
clock:2.39 user:1.70 sys:0.45 swapped:0 exitval:0 max:1812312k

#+END_EXAMPLE
*** Result
PRECIOUS_RESULT algo:mpich numproc:34 msgsize:1596937 hostTime:2.39 hostMem:1812312k simTime:0.577408 
** Test with algorithm impi
*** Command
#+BEGIN_EXAMPLE
smpirun -platform graphene_1024.xml -np 34 ./alltoall 1596937 --cfg=smpi/running_power:20000 --cfg=smpi/alltoall:impi --cfg=maxmin/precision:1e-7
#+END_EXAMPLE
*** raw stdout
#+BEGIN_EXAMPLE
simTime:0.567338 Success numproc=34 msgsize=1596937
#+END_EXAMPLE
*** raw stderr
#+BEGIN_EXAMPLE
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'surf/precision' to '1e-9'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/model' to 'SMPI'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/TCP_gamma' to '4194304'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/running_power' to '20000'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/alltoall' to 'impi'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'maxmin/precision' to '1e-7'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/bw_factor' to '0:0.400976530736138;1420:0.913555534273577;32768:1.07831886657594;65536:0.956083935262915;327680:0.929867998857892'
[0.000000] [surf_parse/INFO] The custom configuration 'network/TCP_gamma' is already defined by user!
[0.000000] [surf_parse/INFO] The custom configuration 'maxmin/precision' is already defined by user!
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/or' to '0:8.14025462333494e-06:8.3958813204998e-10;1420:1.26995184134793e-05:9.09218191293861e-10;32768:3.09570602567453e-05:6.95645307772806e-10;65536:0:0;327680:0:0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/os' to '0:8.9300920419081e-06:7.65438202550106e-10;1420:1.39684254077781e-05:2.97409403415968e-10;32768:1.54082820250394e-05:2.44104034252286e-10;65536:0.000237866424242424:0;327680:0:0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'network/sender_gap' to '0'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/send_is_detached_thres' to '327680'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'workstation/model' to 'compound'
[0.000000] [surf_parse/INFO] The custom configuration 'network/model' is already defined by user!
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/async_small_thres' to '65536'
[0.000000] [xbt_cfg/INFO] Configuration change: Set 'smpi/lat_factor' to '0:1.35489260823384;1420:3.43725032107889;32768:5.72164710873587;65536:11.9885319715471;327680:9.65041953605594'

#+END_EXAMPLE
*** raw timing information
#+BEGIN_EXAMPLE
clock:2.77 user:1.70 sys:0.67 swapped:0 exitval:0 max:1812316k

#+END_EXAMPLE
*** Result
PRECIOUS_RESULT algo:impi numproc:34 msgsize:1596937 hostTime:2.77 hostMem:1812316k simTime:0.567338 
